let uhuanikData = [
  {
    num: 1,
    huagi: "收賄",
    taigiHan: "收烏西錢,收賄",
    taigiLo: "siu oo-se-tsînn,siu-hué",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "收烏西錢",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "收烏西錢袂䆀，嘛會當考慮「受烏西」。",
    phioGiam: "應討論",
    tsuGiam: "收紅包",
    phioThiann: "應討論",
    tsuThiann: "食錢 tsia̍h-tsînn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "口語講「收紅包 siu âng-pau」、「食錢 tsia̍h-tsînn」",
  },
  {
    num: 2,
    huagi: "甲烷",
    taigiHan: "甲烷",
    taigiLo: "kah-uân",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「甲烷 kah-uân」",
  },
  {
    num: 3,
    huagi: "甲醇",
    taigiHan: "甲醇",
    taigiLo: "kah-sûn",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「甲醇 kah-sûn」",
  },
  {
    num: 4,
    huagi: "轉轍器",
    taigiHan: "轉轍器,分道,分道喙",
    taigiLo: "hő-ìn-tò,pun-tō,pun-tō-tshuì",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "轉轍器",
    phioLim: "應討論",
    tsuLim: "建議收分道pun-tō就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "分道/分道喙 pun-tō/pun-tō-tshùi【案：《臺日》有收】",
    phioHo: "認同",
    tsuHo: "贊同分道",
    phioKueh: "認同",
    tsuKueh: "台日有收分道（pun-tō）、分道喙",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「分道 pun-tō」、「分道喙 pun-tō-tshuì」",
  },
  {
    num: 5,
    huagi: "阿茲海默症",
    taigiHan: "阿茲海默症,阿茲海膜",
    taigiLo: "a-tsu-hái-bi̍k-tsìng,a-tsu-hái-mo̍oh",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "討論看覓敢有欲接受「阿茲海膜症a-tsu-hái-mo̍oh-tsìng」，較接近Alzheimer。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "阿茲海默症 A-tsu-hái-bi̍k-tsìng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「阿茲海默症 A-tsu-hái-bi̍k-tsìng」",
  },
  {
    num: 6,
    huagi: "室友",
    taigiHan: "室友,仝蹛的",
    taigiLo: "sik-iú,kâng-tuà--ê",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "室友",
    phioLim: "應討論",
    tsuLim: "建議收室友就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "室友 sik-iú / sit-iú；蹛仝房的 tuà-kāng-pâng--ê",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「室友 sik-iú」、「仝房的 kāng-pâng--ê」",
  },
  {
    num: 7,
    huagi: "和弦",
    taigiHan: "和弦,和絃,靠樂",
    taigiLo: "hô-hiân,khò-lo̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: '華語攏用"弦"，台語有用"絃"。照意思咱愛用「和絃」',
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "和絃 hô-hiân",
    phioHo: "認同",
    tsuHo: "贊同和弦",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「和絃 hô-hiân」",
  },
  {
    num: 8,
    huagi: "乳突病毒",
    taigiHan: "乳突病毒,奶突病毒,奶頭噗病毒,奶頭瘤病毒,起粒病毒",
    taigiLo:
      "jú-tu̍t pēnn-to̍k,ling-thâu-pēnn-to̍k , ling-thâu-liû-pēnn-to̍k,khí-lia̍p-pēnn-to̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "papillomavirus乳頭狀瘤病毒，意思是若像奶頭按呢噗起來的瘤彼款病毒。照字乳突jú-tu̍t病毒無困難。照意思是奶/乳頭噗病毒。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "乳突病毒 jú-tu̍t pēnn-to̍k / lú-tu̍t pīnn-to̍k",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「乳突病毒 jú-tu̍t-pēnn/pīnn-to̍k」",
  },
  {
    num: 9,
    huagi: "影像輔助裁判",
    taigiHan: "影像輔助裁判,影像助判,輔助裁判的影片,影像助理裁判",
    taigiLo:
      "iánn-siōng hú-tsōo tshâi-phuànn, iánn-siōng tsōo phuànn, hú-tsōo tshâi-phuànn ê iánn-phìnn,iánn-siōng tsōo-lí tshâi-phuànn",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議收一个就好。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "影像助判 iánn-siōng tsōo phuànn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「影像輔助裁判 iánn-siōng hú-tsōo tshâi-phuànn」",
  },
  {
    num: 10,
    huagi: "匿名者",
    taigiHan: "匿名者,藏名者,崁名者",
    taigiLo: "li̍k-miâ-tsiá,tshàng-miâ-tsiá,khàm-miâ-tsiá",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "匿名者",
    phioLim: "應討論",
    tsuLim: "會當收兩个，愛討論佗一个為主",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann:
      "匿名者 li̍k-bîng-tsiá / li̍k-miâ-tsiá【案：《臺日》有收「匿名」】",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "台日有收匿名，抑是講「崁名」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「崁名者 khàm-miâ-tsiá」",
  },
  {
    num: 11,
    huagi: "防呆機制",
    taigiHan: "防呆機制,防錯機制,防錯誤機制,安全設計",
    taigiLo:
      "hông-tai ki-tsè,hông-tshò ki-tsè,hông-tshò-gōo ki-tsè,an-tsuân siat-kè",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議收「防呆機制」就好。這款設計比「防止錯誤」有閣較狹的意思。",
    phioGiam: "認同",
    tsuGiam: "防錯機制",
    phioThiann: "應討論",
    tsuThiann: "防錯機制 hông-tshò ki-tsè",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「防錯機制 hông-tshò ki-tsè」",
  },
  {
    num: 12,
    huagi: "熟客",
    taigiHan: "熟似客",
    taigiLo: "si̍k-sāi-kheh",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "主顧客",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "捷來客",
    phioGiam: "應討論",
    tsuGiam: "主顧客",
    phioThiann: "應討論",
    tsuThiann: "主顧客 tsú-kòo-kheh",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「熟似人客 si̍k-sāi lâng-kheh」",
  },
  {
    num: 13,
    huagi: "匿蹤",
    taigiHan: "匿蹤",
    taigiLo: "li̍k-tsong",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "看前後文來決定",
    phioLim: "應討論",
    tsuLim: "建議莫收，看前後文",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "掩蹤 iám-tsong（案：台語有平行的構詞「掩身iám-sin」）",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "隱形",
    phioLoo: "應討論",
    tsuLoo: "建議改做「覕影 bi̍h-iánn」",
  },
  {
    num: 14,
    huagi: "泳衣",
    taigiHan: "泅水衫",
    taigiLo: "siû-tsuí-sann",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "游泳衫",
    phioThiann: "應討論",
    tsuThiann: "游泳衫 iû-íng-sann",
    phioHo: "應討論",
    tsuHo: "也常聽有人說游泳衫",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 15,
    huagi: "宅經濟",
    taigiHan: "宅經濟",
    taigiLo: "the̍h-king-tsè",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "踮跤經濟",
    phioGiam: "認同",
    tsuGiam: "踮厝經濟",
    phioThiann: "應討論",
    tsuThiann:
      "居家經濟 ki-ka king-tsè / ku-ka king-tsè（案：「居家」《臺日》有收）",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「跔厝經濟 ku-tshù king-tsè」",
  },
  {
    num: 16,
    huagi: "網紅",
    taigiHan: "網衝,網紅,網路名人",
    taigiLo: "bāng-tsìng, bāng-âng, bāng-lōo bîng-jîn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "網衝",
    phioTsng: "認同",
    tsuTsng: "網紅",
    phioLim: "應討論",
    tsuLim: "「網衝」若像捷看人咧使用，毋知流通度有夠無",
    phioGiam: "認同",
    tsuGiam: "網衝",
    phioThiann: "應討論",
    tsuThiann:
      "網紅 bāng-âng；網路名人 bāng-lōo bîng-jîn（案：「網紅」權算是直接借。「衝 tshìng」字，有做動詞抑是形容詞的用法，總是，「XX衝」做名詞用，這款類型的構詞敢若較罕得看見。）",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "網紅",
    phioLoo: "應討論",
    tsuLoo:
      "「網路紅人 bāng-lōo âng-lâng」、「網紅 bāng-âng」、「網衝 bāng-tshìng」",
  },
  {
    num: 17,
    huagi: "烹飪",
    taigiHan: "煮食,料理,烹飪",
    taigiLo: "tsú-tsia̍h, liāu-lí, phing-līn",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "料理",
    phioLim: "應討論",
    tsuLim:
      "「烹飪」的意思佮「煮食」應該算是完全對同，閣是習慣講法。料理較捷用佇名詞。",
    phioGiam: "認同",
    tsuGiam: "料理",
    phioThiann: "應討論",
    tsuThiann: "煮食 tsú-tsia̍h、料理 liāu-lí",
    phioHo: "認同",
    tsuHo: "料理",
    phioKueh: "應討論",
    tsuKueh: "煮食",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「煮食 tsú/tsí-tsia̍h」",
  },
  {
    num: 18,
    huagi: "看好度",
    taigiHan: "看好度,贏面度",
    taigiLo: "khuànn-hó-tōo,iânn-bīn-tōo",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "看好度",
    phioLim: "應討論",
    tsuLim: "贏面度",
    phioGiam: "認同",
    tsuGiam: "贏面",
    phioThiann: "應討論",
    tsuThiann: "贏面度 iânn-bīn-tōo",
    phioHo: "認同",
    tsuHo: "看好度",
    phioKueh: "應討論",
    tsuKueh: "贏面度",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「贏面度 」iânn-bīn-tōo",
  },
  {
    num: 19,
    huagi: "置入性行銷",
    taigiHan:
      "置入性行銷,囥入性行銷,硬櫼行銷,暗囥行銷,楔入式行銷,插廣告,插入式廣告",
    taigiLo:
      "tì-ji̍p-sìng hîng-siau, khǹg-ji̍p-sìng hîng-siau,ngē-tsinn hîng-siau,àm-khǹg hîng-siau,seh-ji̍p-sik hîng-siau,tshah kóng-kò,tshah-ji̍p-sik kóng-kò",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "置入性行銷",
    phioLim: "應討論",
    tsuLim: "行銷兩字建議保留",
    phioGiam: "認同",
    tsuGiam: "置入性行銷",
    phioThiann: "應討論",
    tsuThiann: "楔入式廣告/行銷 seh-ji̍p-sik kóng-kò/hîng-siau",
    phioHo: "認同",
    tsuHo: "置入性行銷",
    phioKueh: "認同",
    tsuKueh: "甘字典解釋置（tì）有安置、hē-teh的意思",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「置入性行銷 tì-ji̍p/li̍p-sìng hîng-siau」",
  },
  {
    num: 20,
    huagi: "傭兵",
    taigiHan: "傭兵,倩兵,辛勞兵",
    taigiLo: "iông-ping,tshiànn-ping,sin-lô-ping",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "傭兵",
    phioLim: "應討論",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "傭兵",
    phioThiann: "應討論",
    tsuThiann: "傭兵iông-ping【案：古早有講「傭人」《臺日》嘛有收】",
    phioHo: "認同",
    tsuHo: "傭兵",
    phioKueh: "認同",
    tsuKueh: "台日有傭人（iông-jîn）傭的用法。",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「辛勞兵 sin-lô-ping」",
  },
  {
    num: 21,
    huagi: "巡弋飛彈",
    taigiHan: "巡弋飛彈,巡航飛彈",
    taigiLo: "sûn-ik hui-tuânn,sûn-hâng hui-tuânn",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "巡弋飛彈",
    phioLim: "應討論",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "巡弋飛彈",
    phioThiann: "應討論",
    tsuThiann: "巡弋飛彈 sûn-i̍k hui-tuânn / sûn-i̍k hui-tân",
    phioHo: "認同",
    tsuHo: "巡弋飛彈",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「巡航飛彈 sûn-hâng hui-tuânn」",
  },
  {
    num: 22,
    huagi: "帶風向",
    taigiHan: "帶風向",
    taigiLo: "tài-hong-hiòng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "𤆬風向",
    phioLim: "應討論",
    tsuLim: "𤆬風向(雖然佮方向仝音，毋過台日有收風向，兩條排做伙)",
    phioGiam: "應討論",
    tsuGiam: "引風勢（風向佮方向仝音歹分別）",
    phioThiann: "應討論",
    tsuThiann:
      "起風勢 khí-hōng-sè（案：台語的「起」也有「引𤆬」、「引起」、「指使」的意思，可比講：《教典》就有收「起人做歹 Khí lâng tsò-pháinn.」（教唆犯罪）。）",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「𤆬風頭 tshuā-hong-thâu」",
  },
  {
    num: 23,
    huagi: "大亨",
    taigiHan: "好額人",
    taigiLo: "hó-gia̍h-lâng",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "大好額人",
    phioTsng: "應討論",
    tsuTsng: "大好額人",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "無一定干焦好額",
    phioThiann: "應討論",
    tsuThiann:
      "大色人 tuā-sik-lâng（案：『大亨』，照講毋但「好額」爾，著愛有錢閣有勢）",
    phioHo: "應討論",
    tsuHo:
      '”大亨"毋若好額, 一般koh是某一个產業的成功經營者, 所以會當考慮共大亨翻作"(某一个產業的)頭人"',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「大好額人 tuā hó-gia̍h-lâng」",
  },
  {
    num: 24,
    huagi: "游泳池",
    taigiHan: "泅水池",
    taigiLo: "siû-tsuí-tî",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "游泳池",
    phioThiann: "應討論",
    tsuThiann: "游泳池 iû-íng-tî",
    phioHo: "應討論",
    tsuHo: "也常聽有人說游泳池",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「游泳池 iû-íng-tî」，真捷聽著，教典有收「游泳iû-íng」",
  },
  {
    num: 25,
    huagi: "立式划槳,立槳",
    taigiHan: "徛船,徛船扒,立槳",
    taigiLo: "khiā-tsûn, khiā-tsûn-pê, li̍p-tsiúnn",
    guagi: "SUP Stand Up Paddle",
    tsukai: "張日東老師提供的暫譯",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "立槳",
    phioLim: "應討論",
    tsuLim: "建議收徛式壓槳/徛式划船、徛槳。（台日ah攏用押，教典押、壓分用）",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "徛式划船 khiā-sik kò-tsûn",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "徛式划船",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「徛槳 khiā-tsiúnn」、「徛式划 khiā-sik kò」",
  },
  {
    num: 26,
    huagi: "越位",
    taigiHan: "越位,過位",
    taigiLo: "ua̍t-uī,kuè-uī,ok-sái",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "雖然咱有講超越，毋過「越」佇口語有固定的意思，閣無文白會當區分，所以直接唸無一定較好。",
    phioGiam: "認同",
    tsuGiam: "過位",
    phioThiann: "應討論",
    tsuThiann:
      "越位ua̍t-uī【案：台語有「越權」，「越」字是會當用，無，就講外語offside】",
    phioHo: "認同",
    tsuHo: "若會當接受羅馬字就用ok-sái, 無法度接受羅馬字就用越位",
    phioKueh: "認同",
    tsuKueh:
      "「越位」（Offside）是跤球專有名詞，建議直接採用。甘字典越嘛有跳過的意思。",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "反對",
    tsuSoo: "偷掠雞",
    phioLoo: "應討論",
    tsuLoo: "「越位 ua̍t-uī」",
  },
  {
    num: 27,
    huagi: "鬚鯨類",
    taigiHan: "鬚鯨類,鬚鯃",
    taigiLo: "tshiu-king-luī,tshiu-ngôo",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "建議收「鬚鯨類」就好。哺乳綱>偶蹄目>鯨下目>鬚鯨小目>下面閣分4科(露脊鯨科、新鬚鯨科、灰鯨科、鬚鯨科)，正式分類。台日有用「鯨」。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann:
      "鬚鯨類 tshiu-king-luī【案：「鯨」生物分類通分做「鬚鯨類」佮「齒鯨類」，總是，台語的「鯃」照講罕得用佇「鬚鯨類」，也就是講「鯃」字論真毋是『鯨豚類』的總稱。】",
    phioHo: "應討論",
    tsuHo: "贊同鬚鯃",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「鬚鯨類 tshiu-king-luī」",
  },
  {
    num: 28,
    huagi: "穆斯林",
    taigiHan: "穆斯林,回教徒",
    taigiLo: "bo̍k-su-lîm,mú-sīr-lìm,Huê-kàu-tôo",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議收「穆斯林」就好。回教毋是正式名稱。伊斯蘭教、穆斯林。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "穆斯林 Bok-su-lîm",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「穆斯林 Bo̍k-su-lîm」",
  },
  {
    num: 29,
    huagi: "外遇",
    taigiHan: "外遇,佮人鬥,婚外情,反背婚姻,偷食(臊),飼夥計,設緣投,偷咬雞仔",
    taigiLo:
      "guā-gū, kah lâng tàu,hun-guā-tsîng,huán-puē hun-in,thau-tsia̍h(tsho),tshī hué-kì,siat iân-tâu,thau kā ke-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "婚外情",
    phioLim: "應討論",
    tsuLim:
      "咱有固定性別的講法愛另外處理，遮應該選無分性別的，建議嘛避免各種俗稱。",
    phioGiam: "認同",
    tsuGiam: "婚外情",
    phioThiann: "應討論",
    tsuThiann: "婚外情 hun-guā-tsîng",
    phioHo: "應討論",
    tsuHo: "看情形, 外遇和婚外情",
    phioKueh: "應討論",
    tsuKueh: "偷食",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「婚外情 hun-guā-tsîng」",
  },
  {
    num: 30,
    huagi: "土撥鼠",
    taigiHan: "番鼠",
    taigiLo: "huan-tshí",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "掰塗膨鼠、鼢塗膨鼠",
    phioGiam: "認同",
    tsuGiam: "臺日：番鼠、竹鼠",
    phioThiann: "應討論",
    tsuThiann: "鼢塗鼠 bùn-thôo-tshí / bùn-thôo-tshú",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "掰塗鼠",
    phioTshi: "認同",
    tsuTshi: "小時候說;鼢鼠",
    phioSoo: "",
    tsuSoo: "bùn-tshú",
    phioLoo: "應討論",
    tsuLoo: "建議翻做「鼢塗膨鼠 bùn-thôo-phòng-tshí/tshú」。",
  },
  {
    num: 31,
    huagi: "茶葉蛋",
    taigiHan: "茶葉蛋,茶滷卵",
    taigiLo: "tê-hio̍h-nn̄g,tê-lóo-nn̄g",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "茶滷卵",
    phioLim: "應討論",
    tsuLim: "茶米卵",
    phioGiam: "應討論",
    tsuGiam: "茶米卵",
    phioThiann: "應討論",
    tsuThiann: "茶米卵 tê-bí-nn̄g",
    phioHo: "應討論",
    tsuHo: "茶米滷蛋?",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "茶米卵",
    phioLoo: "應討論",
    tsuLoo: "建議「茶米卵 tê-bí-nn̄g」、「茶蛋 tê-tàn」",
  },
  {
    num: 32,
    huagi: "行人",
    taigiHan: "路人,過路人,行人",
    taigiLo: "lōo-lâng, kuè-lōo-lâng,hîng-jîn",
    guagi: "",
    tsukai: "相關詞彙：人行道",
    phioKhoo: "應討論",
    tsuKhoo: "行路人",
    phioTsng: "應討論",
    tsuTsng: "行路人",
    phioLim: "應討論",
    tsuLim: "建議收過路人就好",
    phioGiam: "應討論",
    tsuGiam: "直接講行人hîng-jîn",
    phioThiann: "認同",
    tsuThiann: "過路人 kuè-lōo-lâng / kè-lōo-lâng",
    phioHo: "應討論",
    tsuHo: '會當考慮直接翻"行人"就好',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "行路人",
    phioLoo: "應討論",
    tsuLoo: "建議講做「過路人 kuè/kè-lōo-lâng」",
  },
  {
    num: 33,
    huagi: "機械手臂",
    taigiHan: "機械手股",
    taigiLo: "ki-hāi tshiú-kóo",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "手股干焦頂橛，手骨才是規肢？",
    phioGiam: "應討論",
    tsuGiam: "機械手",
    phioThiann: "應討論",
    tsuThiann: "機器手骨 ki-khì tshiú-kut",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "機械手",
    phioSoo: "",
    tsuSoo: "機械手",
    phioLoo: "應討論",
    tsuLoo: "建議收「機械手骨 ki-hāi tshiú-kut」",
  },
  {
    num: 34,
    huagi: "果凍",
    taigiHan: "果凍, 水浸粿",
    taigiLo: "kó-tòng, tsuí-tsìm-kué",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "果凍",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "建議收「果凍kó-tàng」，果汁堅凍。嘛會使考慮收「凍果」，堅凍的果汁，通做台語佮華語構詞顛倒反的例。",
    phioGiam: "認同",
    tsuGiam: "kó-tàng",
    phioThiann: "應討論",
    tsuThiann: "菜燕 tshài-iàn",
    phioHo: "應討論",
    tsuHo: "會當討論看菜燕敢有適合",
    phioKueh: "應討論",
    tsuKueh: "雖講有方音差，毋過tàng敢若較捷聽",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "果凍",
    phioLoo: "應討論",
    tsuLoo: "建議收「果凍 kó-tàng」",
  },
  {
    num: 35,
    huagi: "收回扣",
    taigiHan: "收回扣",
    taigiLo: "siu huê-khàu",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "commission",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "收khoo-mí-sióng",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "收khoo-mí-sióng",
    phioHo: "應討論",
    tsuHo: "提khoo-mi-siong?",
    phioKueh: "應討論",
    tsuKueh: "回收圈（khian）",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "收傭金",
    phioLoo: "應討論",
    tsuLoo: "一般聽著的是「收 khoo-mí-sióng」",
  },
  {
    num: 36,
    huagi: "栓塞",
    taigiHan: "栓窒,血角",
    taigiLo: "sng-that,hueh-kak",
    guagi: "",
    tsukai:
      "血管內的固體、液體或氣體團塊隨血流被運送到遠端並造成血流阻塞。慈濟醫院教學影片將「經動脈血管栓塞治療術」講做「經過動脈共血筋窒起來治療手術」 https://www.youtube.com/watch?v=h2sfaknHs-4&ab_channel=%E5%A4%A7%E6%9E%97%E6%85%88%E6%BF%9F%E9%86%AB%E9%99%A2%E6%95%99%E5%AD%B8%E7%A0%94%E7%99%BC%E7%B5%84",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "『栓』應該是取『瓶栓』的意思，用台語來描述這个詞是「像窒仔窒牢咧的狀態」。sng/tshng/tshuan攏是門栓仔的意思。",
    phioGiam: "應討論",
    tsuGiam: "窒血管",
    phioThiann: "應討論",
    tsuThiann: "窒that",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議照字講做「栓塞sng-sat」",
  },
  {
    num: 37,
    huagi: "追劇",
    taigiHan: "痟連續劇",
    taigiLo: "siáu liân-sio̍k-kio̍k",
    guagi: "",
    tsukai: "【台語聽有無】追劇追星相關台語按怎講",
    phioKhoo: "應討論",
    tsuKhoo: "追劇",
    phioTsng: "應討論",
    tsuTsng: "追劇，逐劇",
    phioLim: "應討論",
    tsuLim: "建議「追劇」就好",
    phioGiam: "應討論",
    tsuGiam: "追劇",
    phioThiann: "應討論",
    tsuThiann: "追劇 tui-kio̍k / tui-ki̍k",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "追劇",
    phioLoo: "應討論",
    tsuLoo: "建議直接照華語講做「追劇 tui-kio̍k/ki̍k」",
  },
  {
    num: 38,
    huagi: "追星",
    taigiHan: "痟明星",
    taigiLo: "siáu bîng-tshenn",
    guagi: "",
    tsukai: "【台語聽有無】追劇追星相關台語按怎講",
    phioKhoo: "應討論",
    tsuKhoo: "逐明星",
    phioTsng: "應討論",
    tsuTsng: "追星，逐明星",
    phioLim: "應討論",
    tsuLim: "建議「追星」就好",
    phioGiam: "應討論",
    tsuGiam: "追星",
    phioThiann: "應討論",
    tsuThiann: "追星 tui-tshenn / tui-tshinn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議比照華語講做「追明星 tui-bîng-tshenn/tshinn」",
  },
  {
    num: 39,
    huagi: "霧淞",
    taigiHan: "冰花",
    taigiLo: "ping-hue",
    guagi: "",
    tsukai:
      "霧凇，也稱樹掛或霧凍，是一種在天氣寒冷的地方出現的白色不透明晶體。",
    phioKhoo: "應討論",
    tsuKhoo: "霧淞",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "霧冰or霧霜 (https://www.moedict.tw/%E5%87%87)",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "凍霧 tàng-bū",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "有聽人講過「冰粉」",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「霧霜 bū-sng」",
  },
  {
    num: 40,
    huagi: "慢箋",
    taigiHan: "慢簽,慢單,慢性病藥單,慢病藥單,慢性病長期藥單,長期藥單",
    taigiLo:
      "bān-tshiam,bān-tuann,bān-sìng-pēnn io̍h-tuann,bān-pēnn io̍h-tuann,bān-sìng-pēnn tn̂g-kî io̍h-tuann,tn̂g-kî io̍h-tuann",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "慢性病連續處方箋>慢箋(照字)。慢性病連續藥單>慢單(翻譯)。",
    phioGiam: "認同",
    tsuGiam: "慢性病藥單",
    phioThiann: "應討論",
    tsuThiann: "慢性病長期藥單 bān-sìng-pēnn tn̂g-kî io̍h-tuann",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "慢性病藥單",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「慢性病藥單 bān-sìng-pēnn/pīnn io̍h-tuann」",
  },
  {
    num: 41,
    huagi: "半邊小臉症",
    taigiHan: "面大細䫌症",
    taigiLo: "bīn tuā-sè phué tsìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議「半爿細䫌症」",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "半爿細面症 puànn-pîng sè-bīn-tsìng",
    phioHo: "應討論",
    tsuHo: '加一個"症"讀起來敢若怪怪?',
    phioKueh: "應討論",
    tsuKueh: "半面麻痺？",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「䫌」補收「phé」的腔口差",
  },
  {
    num: 42,
    huagi: "級距、階層",
    taigiHan: "坎級",
    taigiLo: "khám-kip",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "華語是欲收佗一个？級距→級差kip-tsha，階層→階層kai-tsân",
    phioGiam: "應討論",
    tsuGiam: "gám",
    phioThiann: "應討論",
    tsuThiann: "坎 kám / gám",
    phioHo: "應討論",
    tsuHo: '看前後文, 有時直接用"坎"就好. 例如"一坎差幾分".',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "級數",
    phioSoo: "應討論",
    tsuSoo: "等級",
    phioLoo: "應討論",
    tsuLoo: "建議收「級差 kip-tsha」，「階層」佮「級距」意思無仝",
  },
  {
    num: 43,
    huagi: "打靶",
    taigiHan: "打靶",
    taigiLo: "tánn-pé",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "看軍中敢有台語講法",
    phioTsng: "應討論",
    tsuTsng: "參考軍隊的習慣用法",
    phioLim: "應討論",
    tsuLim: "建議用傳統詞「考銃」，若是箭就「考箭」，賰的類推。",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "考銃 khó-tshìng",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議改做「考銃 khó-tshìng」",
  },
  {
    num: 44,
    huagi: "沉浸式",
    taigiHan: "浸水式",
    taigiLo: "tsìm-tsuí-sik",
    guagi: "",
    tsukai: "沉浸式教學、沉浸式體驗",
    phioKhoo: "應討論",
    tsuKhoo: "沉浸式",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議用「沉浸式」就好",
    phioGiam: "應討論",
    tsuGiam: "浸潤式較好發音",
    phioThiann: "應討論",
    tsuThiann:
      "浸汰式tsìm-thuā-sik；沉浸式tîm-tsìm-sik（案：台語的「汰thuā」才有『受到他人或環境的影響而學習或改變』。「浸水」這款述賓的語義較具體，無合台語人的語感。）",
    phioHo: "應討論",
    tsuHo: "個人沒意見, 但常聽有人不贊同這種翻譯.",
    phioKueh: "應討論",
    tsuKueh: "沉浸式",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "全語境(教學)",
    phioLoo: "應討論",
    tsuLoo: "是抽象的概念，建議直接講做「沉浸式 tîm-tsìm-sik」",
  },
  {
    num: 45,
    huagi: "面罩",
    taigiHan: "面罨",
    taigiLo: "bīn-am, bīn-om",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "「面罩bīn-tà」敢袂使？",
    phioGiam: "應討論",
    tsuGiam: "面罩",
    phioThiann: "應討論",
    tsuThiann: "面罩 bīn-tà / bīn-tàu",
    phioHo: "應討論",
    tsuHo: "常聽人說面罩",
    phioKueh: "應討論",
    tsuKueh: "語感感覺罩較大，像蠓罩",
    phioTshi: "應討論",
    tsuTshi: "面罩",
    phioSoo: "應討論",
    tsuSoo: "面罩",
    phioLoo: "應討論",
    tsuLoo: "建議收「面罩 bīn-tà」",
  },
];
