const uhuanikData = [
  {
    num: 1,
    huagi: "易科罰金",
    taigiHan: "易科罰金",
    taigiLo: "i̍k-kho hua̍t-kim",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 2,
    huagi: "石滬",
    taigiHan: "石滬",
    taigiLo: "tsio̍h-hōo",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 3,
    huagi: "海洛因",
    taigiHan: "海洛因,四號仔",
    taigiLo: "Hái-lo̍k-in,sì-hō-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "海洛因",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "建議收海洛因就好(heroin)",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "羅馬字「hái-lo̍k-in」免大寫",
  },
  {
    num: 4,
    huagi: "安非他命",
    taigiHan: "安非他命",
    taigiLo: "An-hui Tha-bīng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "民間稱「安仔」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "羅馬字「an-hui-tha-bīng」免大寫",
  },
  {
    num: 5,
    huagi: "焚化爐",
    taigiHan: "焚化爐",
    taigiLo: "hûn-huà-lôo",
    guagi: "",
    tsukai: "教典有收",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 6,
    huagi: "牛棚",
    taigiHan: "牛棚",
    taigiLo: "gû-pênn,gû-pînn",
    guagi: "Bullpen",
    tsukai:
      "牛棚（英語：Bullpen）是棒球場中投手上場前暖身練投的區域，也被引申用來指稱隊上的後援投手群。",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "gû-pênn/pînn",
    phioGiam: "認同",
    tsuGiam: "牛牢",
    phioThiann: "認同",
    tsuThiann: "牛棚 gû-pênn / gû-pînn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "通行腔「gû-pênn」",
  },
  {
    num: 7,
    huagi: "台積電",
    taigiHan: "台積電",
    taigiLo: "Tâi-tsik-tiān",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "應該免討論",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 8,
    huagi: "聯合國",
    taigiHan: "聯合國",
    taigiLo: "Liân-ha̍p-kok",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "應該免討論",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 9,
    huagi: "惡性腫瘤",
    taigiHan: "惡性腫瘤,惡性瘤",
    taigiLo: "ok-sìng tsìng-liû, ok-sìng liû",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "建議收惡性腫瘤就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「惡性腫瘤」",
  },
  {
    num: 10,
    huagi: "淨零排放",
    taigiHan: "淨零排放",
    taigiLo: "tsīng-lîng pâi-hòng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 11,
    huagi: "溫室氣體",
    taigiHan: "溫室氣體",
    taigiLo: "un-sik khì-thé",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 12,
    huagi: "溫室效應",
    taigiHan: "溫室效應",
    taigiLo: "un-sik hāu-ìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 13,
    huagi: "外役監",
    taigiHan: "外役監",
    taigiLo: "guā-i̍k-kann",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "外役監 guā-ia̍h-kann（案：「外役」古早就有講「guā-ia̍h」）",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 14,
    huagi: "邊境",
    taigiHan: "邊境",
    taigiLo: "pian-kíng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 15,
    huagi: "視神經",
    taigiHan: "視神經",
    taigiLo: "sī-sîn-king",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 16,
    huagi: "角膜",
    taigiHan: "角膜,眼明衣",
    taigiLo: "kak-mo̍oh,gán-bîng-i",
    guagi: "cornea",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "建議收角膜就好(cornea)",
    phioGiam: "認同",
    tsuGiam: "角膜",
    phioThiann: "認同",
    tsuThiann: "角膜 kak-mo̍oh",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "收「角膜 kak-mo̍oh」就好",
  },
  {
    num: 17,
    huagi: "游擊隊",
    taigiHan: "游擊隊",
    taigiLo: "iû-kik-tuī",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 18,
    huagi: "製程",
    taigiHan: "製程",
    taigiLo: "tsè-thîng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "製程 tsè-tîng / tsè-thîng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 19,
    huagi: "挖角人才",
    taigiHan: "挖人才",
    taigiLo: "óo jîn-tsâi",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: '(華)"挖角">"(台)挖人才',
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "又音「ué lîng-tsâi」",
  },
  {
    num: 20,
    huagi: "分析師",
    taigiHan: "分析師",
    taigiLo: "hun-sik-su",
    guagi: "",
    tsukai: "半冬內的字頻 221 改，財經新聞常用詞",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 21,
    huagi: "山友",
    taigiHan: "山友",
    taigiLo: "suann-iú",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 22,
    huagi: "鋒面",
    taigiHan: "鋒面",
    taigiLo: "hong-bīn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 23,
    huagi: "勒斃,勒死",
    taigiHan: "摧死",
    taigiLo: "tshui--sí",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 24,
    huagi: "炸物",
    taigiHan: "糋路",
    taigiLo: "tsìnn-lōo",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 25,
    huagi: "復刻",
    taigiHan: "復刻",
    taigiLo: "ho̍k-khik",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "ho̍k-khik",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "羅馬字愛改做「ho̍k-khik」",
  },
  {
    num: 26,
    huagi: "霸凌",
    taigiHan: "霸凌",
    taigiLo: "pà-lîng",
    guagi: "bully",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "「霸性」+「凌遲」=霸凌",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 27,
    huagi: "太陽能板",
    taigiHan: "太陽能枋",
    taigiLo: "thài-iông-lîng pang",
    guagi: "",
    tsukai: "板/枋 問題欲按怎處理？",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 28,
    huagi: "寄養家庭",
    taigiHan: "寄養家庭",
    taigiLo: "kià-ióng ka-tîng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 29,
    huagi: "偵查氣球",
    taigiHan: "偵查氣球,偵查雞胿",
    taigiLo: "tsing-tsa khì-kiû,tsing-tsa ke-kui",
    guagi: "",
    tsukai: "教典有雞胿無氣球",
    phioKhoo: "認同",
    tsuKhoo: "偵查雞胿",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "偵查氣球就好",
    phioGiam: "認同",
    tsuGiam: "偵查氣球",
    phioThiann: "認同",
    tsuThiann: "偵查氣球 tsing-tsa khì-kiû",
    phioHo: "認同",
    tsuHo: "贊同偵查雞胿",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "建議收「偵查氣球 tsing-tsa khì-kiû」",
  },
  {
    num: 30,
    huagi: "物聯網",
    taigiHan: "物聯網",
    taigiLo: "bu̍t-liân-bāng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 31,
    huagi: "少子化",
    taigiHan: "少子化",
    taigiLo: "siáu-tsú-huà",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 32,
    huagi: "視網膜",
    taigiHan: "目睭膜,視網膜",
    taigiLo: "ba̍k-tsiu-mo̍oh,sī-bāng-mo̍oh",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "視網膜",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "建議收視網膜就好",
    phioGiam: "認同",
    tsuGiam: "視網膜",
    phioThiann: "認同",
    tsuThiann: "視網膜 sī-bāng-mo̍oh",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "視網膜",
    phioLoo: "認同",
    tsuLoo: "建議收「視網膜 sī-bāng-mo̍oh」較精確。",
  },
  {
    num: 33,
    huagi: "脊髓",
    taigiHan: "龍骨髓",
    taigiLo: "lîng-kut-tshué",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "龍骨髓 liông-kut-tshué / lîng-kut-tshé",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "又音「lîng-kut-tshé」",
  },
  {
    num: 34,
    huagi: "瀏覽器",
    taigiHan: "瀏覽器",
    taigiLo: "liû-lám-khì",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 35,
    huagi: "填海造陸",
    taigiHan: "坉海造陸",
    taigiLo: "thūn-hái tsō-lio̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "坉海造地",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "填海造地",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 36,
    huagi: "臍帶",
    taigiHan: "肚臍帶,臍帶",
    taigiLo: "tōo-tsâi-tuà,tsâi-tuà",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "肚臍帶",
    phioTsng: "認同",
    tsuTsng: "臍帶",
    phioLim: "認同",
    tsuLim: "臍帶就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "臍帶 tsâi-tuà",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "臍帶",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 37,
    huagi: "熊市",
    taigiHan: "熊市",
    taigiLo: "hîm-tshī",
    guagi: "",
    tsukai: "金融尬台語",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 38,
    huagi: "牛市",
    taigiHan: "牛市",
    taigiLo: "gû-tshī",
    guagi: "",
    tsukai: "金融尬台語",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 39,
    huagi: "制衡",
    taigiHan: "制衡",
    taigiLo: "tsè-hîng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 40,
    huagi: "瀕危,瀕臨絕種",
    taigiHan: "強欲絕種",
    taigiLo: "kiông-beh tsua̍t-tsíng",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "建議音改tse̍h-tsíng",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann:
      "「絕種」在來是講「tse̍h-tsíng」較四常，比論講：孤毛絕種 koo-môo-tse̍h-tsíng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 41,
    huagi: "乳管原位癌",
    taigiHan: "奶管原位癌",
    taigiLo: "ling-kóng guân-uī-gâm",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "ling-kńg",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann:
      "「管」讀「kńg」較好（案：身軀的一般是講kńg，比論講：血管hueh/huih-kńg、肺管hì-kńg）",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議標音改做「奶管原位癌ling-kńg guân-uī-gâm」",
  },
  {
    num: 42,
    huagi: "焦慮症",
    taigiHan: "焦慮症",
    taigiLo: "tsiau-lū-tsìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "焦慮症 tsiau-lī-tsìng / tsiau-lū-tsìng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "操慮症（tshau-lū-tsìng）",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「操煩症tshau-huân-tsìng」",
  },
  {
    num: 43,
    huagi: "遊戲",
    taigiHan: "遊戲",
    taigiLo: "iû-hì",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: "看情形. 有時或可與「耍/奕」搭配使用",
    phioKueh: "認同",
    tsuKueh: "台日有收",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 44,
    huagi: "人工智慧",
    taigiHan: "人工智慧",
    taigiLo: "lâng-kang tì-huī",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "建議發音用jîn-kang。lâng-kang是人手的意思",
    phioThiann: "認同",
    tsuThiann: "「人工」jîn-kang較合",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 45,
    huagi: "性騷擾",
    taigiHan: "性騷擾",
    taigiLo: "sìng-so-jiáu",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann:
      "台語的「狗鯊」自來是查埔的共查某的狗鯊，罕得聽見顛倒頭用的。現代社會的「性騷擾」意思較闊。",
    phioHo: "應討論",
    tsuHo: "有人用狗鯊/弄狗鯊",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "又音「sìng-so-liáu」",
  },
  {
    num: 46,
    huagi: "截圖",
    taigiHan: "截圖, 掠圖,閘圖",
    taigiLo: "tsia̍t-tôo, lia̍h-tôo,tsa̍h-tôo",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "建議收截圖就好",
    phioGiam: "認同",
    tsuGiam: "截圖",
    phioThiann: "應討論",
    tsuThiann: "摘圖 tiah-tôo",
    phioHo: "認同",
    tsuHo: "贊成掠圖(名詞)/圖掠落來(動詞)",
    phioKueh: "認同",
    tsuKueh: "掠圖",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "建議直接收「截圖 tsia̍t-tôo」",
  },
  {
    num: 47,
    huagi: "小耳症",
    taigiHan: "小耳症",
    taigiLo: "sió-hīnn-tsìng",
    guagi: "",
    tsukai: "sió/siáu？",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "細耳症 sè-hīnn-tsìng / suè-hī-tsìng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 48,
    huagi: "助聽器",
    taigiHan: "助聽器",
    taigiLo: "tsōo-thiann-khì",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "助聽機",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 49,
    huagi: "創傷後壓力症候群",
    taigiHan: "創傷後壓力症候群",
    taigiLo: "tshòng-siong āu ap-li̍k tsìng-hāu-kûn",
    guagi: "PTSD",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "tshong-siong",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "創tshong，著傷意思的「創」，照講是陰平較好",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「創傷」標音改做「tshong-siong」",
  },
  {
    num: 50,
    huagi: "子宮肌瘤",
    taigiHan: "子宮肌瘤",
    taigiLo: "tsú-kiong-ki-liû",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "子宮肉瘤 tsú-kiong bah-liû（面頂有重複）",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 51,
    huagi: "共融公園",
    taigiHan: "共融公園",
    taigiLo: "kiōng-Iông kong-hn̂g",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 52,
    huagi: "共融遊戲場",
    taigiHan: "共融遊戲場",
    taigiLo: "kiōng-Iông iû-hì-tiûnn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 53,
    huagi: "鷹派",
    taigiHan: "鷹派",
    taigiLo: "ing-phài",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「強硬派 kiông-ngē/ngī-phài」",
  },
  {
    num: 54,
    huagi: "鴿派",
    taigiHan: "鴿派",
    taigiLo: "kap-phài",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "台日有收誠濟鴿",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「溫和派 un-hô-phài」",
  },
  {
    num: 55,
    huagi: "口碑",
    taigiHan: "口碑",
    taigiLo: "kháu-pi",
    guagi: "",
    tsukai: "台日典詞彙",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "台日有收「口碑」，名聲",
    phioTshi: "認同",
    tsuTshi: "風評",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "臺日有收",
  },
  {
    num: 56,
    huagi: "演算法",
    taigiHan: "演算法, 計算法",
    taigiLo: "ián-suàn-huat, kè-suàn-huat",
    guagi: "algorithm",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "演算法就好",
    phioGiam: "認同",
    tsuGiam: "ián-sǹg-huat",
    phioThiann: "認同",
    tsuThiann: "演算法 ián-suàn-huat",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "演算法",
    phioLoo: "認同",
    tsuLoo: "收「演算法」就好",
  },
  {
    num: 57,
    huagi: "碳足跡",
    taigiHan: "碳跤跡",
    taigiLo: "thuànn-kha-jiah",
    guagi: "Carbon footprint",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 58,
    huagi: "社畜",
    taigiHan: "社畜",
    taigiLo: "siā-thiok",
    guagi: "",
    tsukai:
      "社畜（日語：社畜／しゃちく Shachiku）是日本企業底層上班族的自嘲用語，源於「會社」與「家畜」，意思為「公司的牲畜」，最早出現在1990年代的日本，隨後在東亞逐漸流行。",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "音讀建議用siā-thik",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "社畜 siā-thik / siā-thiok",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "愛補又音「siā-thik」",
  },
  {
    num: 59,
    huagi: "彗星",
    taigiHan: "彗星",
    taigiLo: "huī-tshinn, huī-tshenn",
    guagi: "",
    tsukai:
      "教典有長尾星、掃帚星、疶屎星，無收彗星。公視新聞 kah 逐工一幅天文圖攏會講彗星",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "huī-tshenn",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "彗星 huī-tshenn / huī-tshinn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "教典收掃帚手、落屎星，毋過個人認為應該會用得直接講「慧星」較中性",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 60,
    huagi: "翻拍, 翻攝",
    taigiHan: "翻翕,轉翕",
    taigiLo: "huan-hip,tsuán-hip",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "翻翕",
    phioLim: "應討論",
    tsuLim: "建議收翻翕就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann:
      "轉翕 tsuán-hip（案：『翻拍』論真該當是『複製』爾，毋過台語的「翻」有改變的意思。）",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「轉翕 tsuán-hip」就好",
  },
  {
    num: 61,
    huagi: "粉絲專頁",
    taigiHan: "迷眾頁",
    taigiLo: "bê-tsiòng-ia̍h",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann:
      "迷眾專頁 bê-tsiòng tsuan-ia̍h（案：華語的『粉絲專業』嘛會當簡稱『粉專』，按呢共看「專」字有譯出來照講較好。也就是咱嘛通對應簡稱做「迷專」。）",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「迷眾專頁 bê-tsiòng tsuan-ia̍h」",
  },
  {
    num: 62,
    huagi: "職場",
    taigiHan: "工課場,職場",
    taigiLo: "khang-khuè-tiûnn,tsit-tiûnn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "職場",
    phioLim: "應討論",
    tsuLim: "兩个攏好，討論看欲佗一个做頭前",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "工課場 khang-khuè-tiûnn / khang-khè-tiûnn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「工課場 khang-khuè/khè-tiûnn」就好",
  },
  {
    num: 63,
    huagi: "蓄水",
    taigiHan: "儉水,蓄水",
    taigiLo: "khiām-tsuí,thiok-tsuí",
    guagi: "",
    tsukai: "相關詞彙：蓄水設備、蓄水率、蓄水池、蓄水量",
    phioKhoo: "認同",
    tsuKhoo: "thiok-tsuí",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "敢會當講「囤水(tún-tsuí)」？",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "儉水 khiām-tsuí",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "存水",
    phioLoo: "認同",
    tsuLoo: "收「儉水khiām-tsuí」",
  },
  {
    num: 64,
    huagi: "房仲",
    taigiHan: "賣厝中人",
    taigiLo: "bē-tshù tiong-lâng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議華語收『仲介』、台語對「中人」就好。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "中人就好, 毋免賣厝, 因為可能也是買厝",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "中人",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 65,
    huagi: "打工",
    taigiHan: "做散工",
    taigiLo: "tsò-suánn-kang",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: '看情形, 如在超市可翻作"做點鐘工"',
    phioKueh: "認同",
    tsuKueh: "抑是「臨時工」、「雜差仔工」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 66,
    huagi: "受孕困難",
    taigiHan: "歹牢胎",
    taigiLo: "pháinn-tiâu-the",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "花袂牢枝 hue-bē-tiâu-ki",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "傳統的講法是「花袂牢枝hue-bē-tiâu-ki」",
  },
  {
    num: 67,
    huagi: "打卡",
    taigiHan: "頓卡",
    taigiLo: "tǹg-khah",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "拍卡",
    phioLim: "應討論",
    tsuLim: "「拍卡」應該已經通行矣",
    phioGiam: "應討論",
    tsuGiam: "tánn-khah /phah-khah",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo:
      "頓的動作和打卡的動作kan-na無真相siāng，會當考慮直接用打卡(tánn-khah)就好.",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 68,
    huagi: "腹地",
    taigiHan: "腹地",
    taigiLo: "pak-tē",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: '也有聽過人用文音讀"ho̍k"-tē',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 69,
    huagi: "人潮",
    taigiHan: "人陣",
    taigiLo: "lâng-tīn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "人潮jîn-tiâu",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: '會當考慮直接翻"人潮"就好',
    phioKueh: "應討論",
    tsuKueh: "jîn-tiâu",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 70,
    huagi: "閣揆",
    taigiHan: "閣揆",
    taigiLo: "koh-kuî",
    guagi: "",
    tsukai: "教典有「內閣」、「閣員」詞目，無收 揆",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "甘字典有解釋「揆」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "行政院長",
    phioLoo: "應討論",
    tsuLoo: "建議標音改做「koh-kuî」",
  },
  {
    num: 71,
    huagi: "彈性上班",
    taigiHan: "彈性上班",
    taigiLo: "tân-sìng siōng-pan",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議莫收，照前後文講「補班」",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "伸勼上班",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 72,
    huagi: "個資外洩",
    taigiHan: "個資外洩,個資漏洩",
    taigiLo: "kò-tsu guā-sia̍p,kò-tsu lāu-sia̍p　",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "建議收個資漏洩就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "個資漏洩 kóo-tsu lāu-sia̍p",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "個資漏洩",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「個資漏洩 kò-tsu lāu-sia̍p」",
  },
  {
    num: 73,
    huagi: "疫情再起,疫情復發",
    taigiHan: "疫情翻箍",
    taigiLo: "i̍k-tsîng huan-khoo",
    guagi: "",
    tsukai: "疫情翻箍",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "疫情再起(i̍k-tsîng tsài khí)。翻箍敢會當按呢用？？",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "倒頭槌",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "臺日有收「翻箍 huan-khoo」，舉例「病閣翻箍」",
  },
  {
    num: 74,
    huagi: "疫情趨緩",
    taigiHan: "疫情轉和",
    taigiLo: "i̍k-tsîng tńg-hô",
    guagi: "",
    tsukai: "疫情轉和",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "疫情較坐 i̍k-tsîng kah tshē",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "疫情「敨剝」、「消敨」",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 75,
    huagi: "充電樁",
    taigiHan: "充電柱仔",
    taigiLo: "tshiong-tiān thiāu-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議免「仔」",
    phioGiam: "認同",
    tsuGiam: "毋免「仔」",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "充電柱",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "充電柱",
    phioLoo: "應討論",
    tsuLoo: "比照「電火柱」，講做「充電柱 tshiong-tiān-thāu」就好",
  },
  {
    num: 76,
    huagi: "輿論",
    taigiHan: "輿論,公論",
    taigiLo: "ú-lūn,kong-lūn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "輿論",
    phioTsng: "認同",
    tsuTsng: "公論",
    phioLim: "應討論",
    tsuLim: "公論",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "公論 kong-lūn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "與論",
    phioLoo: "應討論",
    tsuLoo: "建議收「公論」",
  },
  {
    num: 77,
    huagi: "阿基里斯腱",
    taigiHan: "跤後筋",
    taigiLo: "kha-āu-kin",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "後跤筋？",
    phioTshi: "應討論",
    tsuTshi: "後跤筋",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「跤後蹬肌腱 kha-āu-tenn/tinn ki-kiān」，「筋」佮「肌腱」無仝",
  },
  {
    num: 78,
    huagi: "澄清",
    taigiHan: "掰會",
    taigiLo: "pué-huē",
    guagi: "",
    tsukai: "教典有收「澄清 tîng-tshing」",
    phioKhoo: "應討論",
    tsuKhoo: "澄澄清",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議「澄清 tîng-tshing」、「掰會pué-huē/pé-hē」攏收",
  },
  {
    num: 79,
    huagi: "背包客",
    taigiHan: "揹仔跤,揹仔客",
    taigiLo: "phāinn-á-kha,phāinn-á-kheh",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "揹仔客",
    phioLim: "應討論",
    tsuLim: "建議收「揹仔客」就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "揹仔客 phāinn-á-kheh",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "揹仔客",
    phioLoo: "應討論",
    tsuLoo: "收「揹仔客 phāinn-á-kheh」",
  },
  {
    num: 80,
    huagi: "房貸",
    taigiHan: "房貸,厝貸",
    taigiLo: "pâng-tāi,tshù-tāi",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "厝貸",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議收「厝貸」",
    phioGiam: "認同",
    tsuGiam: "厝期",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "房貸",
    phioLoo: "應討論",
    tsuLoo: "收「房貸pâng-tāi」",
  },
  {
    num: 81,
    huagi: "積木",
    taigiHan: "柴角仔,柴疊仔",
    taigiLo: "tshâ-kak-á,tshâ-thia̍p-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "柴疊仔",
    phioLim: "應討論",
    tsuLim: "建議收「柴角仔」",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "柴角仔 tshâ-kak-á",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "收「柴角仔tshâ-kak-á」",
  },
  {
    num: 82,
    huagi: "驅逐",
    taigiHan: "驅逐",
    taigiLo: "khu-tio̍k",
    guagi: "",
    tsukai: "相關詞彙：驅逐艦、驅逐令",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議莫收，看前後文用「趕」就會使",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann:
      "「驅逐」khu-tio̍k / khi-tio̍k；除去照字讀口語也會當講「趕kuánn」。若驅逐艦《臺日》有收「驅激艦」khu-kik-lām / khi-kek-lām",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 83,
    huagi: "子宮肌瘤",
    taigiHan: "子宮筋瘤,子宮肌瘤",
    taigiLo: "tsú-kiong kin-liû,tsú-kiong ki-liû",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "收子宮肌瘤就好。這條重複",
    phioGiam: "應討論",
    tsuGiam: "子宮肉瘤",
    phioThiann: "應討論",
    tsuThiann: "子宮肉瘤 tsú-kiong bah-liû",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議照字「子宮肌瘤tsú-kiong-ki-liû」",
  },
  {
    num: 84,
    huagi: "魚子醬",
    taigiHan: "魚卵醬",
    taigiLo: "hî-nn̄g-tsiùnn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議用魚子醬hî-tsú-tsiùnn就好",
    phioGiam: "應討論",
    tsuGiam: "魚子醬 hî-tsí tsiùnn",
    phioThiann: "應討論",
    tsuThiann: "魚子醬 hî-tsí-tsiùnn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "臺語有烏魚子，建議講做「魚子醬hî-tsí-tsiùnn」",
  },
  {
    num: 85,
    huagi: "嚮導",
    taigiHan: "嚮導",
    taigiLo: "hiáng-tō",
    guagi: "",
    tsukai: "台文華文線頂辭典",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議用「𤆬路的」",
    phioGiam: "認同",
    tsuGiam: "引路人",
    phioThiann: "應討論",
    tsuThiann: "𤆬路的 tshuā-lōo--ê",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "𤆬路人",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "照字愛標做「hiòng-tō」",
  },
  {
    num: 86,
    huagi: "還税於民",
    taigiHan: "還税於民",
    taigiLo: "hîng-suè-î-bîn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "還稅予百姓 hîng suè hōo peh-sènn / hîng sè hōo peh-sìnn",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「稅還人民suè hîng jîn-bîn/sè hîng lîn-bîn」",
  },
  {
    num: 87,
    huagi: "辣椒水",
    taigiHan: "薟椒仔水",
    taigiLo: "hiam-tsio-á tsuí",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "番薑水",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "因為番薑仔的講法誠濟，後面攏會當加「水」，建議莫收",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「辣椒」臺語方言詞真濟，建議直接講做「辣椒水lua̍h-tsio-tsuí」",
  },
  {
    num: 88,
    huagi: "側面",
    taigiHan: "邊仔面",
    taigiLo: "pinn-á bīn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "邊仔 邊仔爿",
    phioThiann: "應討論",
    tsuThiann: "坦邊 tán-pinn",
    phioHo: "應討論",
    tsuHo: "邊仔(四邊邊仔)或許比邊仔面更貼近台語構詞習慣?",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 89,
    huagi: "熱脹冷縮",
    taigiHan: "熱脹冷縮",
    taigiLo: "jia̍t-tiòng líng-sok",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "燒膨冷縮sio-phòng-líng-sok",
    phioGiam: "認同",
    tsuGiam: "脹 tiùnn",
    phioThiann: "認同",
    tsuThiann: "熱脹冷縮 jia̍t-tiòng-líng-sok",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「燒脹冷縮sio-tiòng-líng-sok」",
  },
  {
    num: 90,
    huagi: "快遞",
    taigiHan: "快遞",
    taigiLo: "khuài-tē",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "快送",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "快送",
    phioThiann: "應討論",
    tsuThiann: "快送 khuài-sàng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "台日有「遞送」抑是講「快送」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「快送khuài-sàng」",
  },
  {
    num: 91,
    huagi: "心肌梗塞",
    taigiHan: "心肌窒",
    taigiLo: "sim-ki-that",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "心肌梗塞 sim-ki kīng-sik（案：梗塞kīng-sik，《臺日》有收）",
    phioHo: "應討論",
    tsuHo: "窒心肌是否更符合台語構詞?",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "心臟麻痺",
    phioLoo: "應討論",
    tsuLoo: "聽著的是「心肌梗窒 sim-ki-kénn/kínn-that」",
  },
  {
    num: 92,
    huagi: "大雨特報,豪雨特報,大豪雨特報,超大豪雨特報",
    taigiHan: "大雨特報,大水雨特報,超大水雨特報,盡磅大水雨特報",
    taigiLo:
      "tuā-hōo ti̍k-pò,tuā-tsuí-hōo ti̍k-pò,tshiau-tuā-tsuí-hōo ti̍k-pò,tsīn-pōngtuā-tsuí-hōo ti̍k-pò",
    guagi: "",
    tsukai:
      "中央氣象局的大雨特報有分四級，目前的翻譯是邱文錫老師建議使用的氣象詞彙。 另外中央氣象局 167 氣象預報專線台語版會講文讀音「豪雨特報 hô-ú ti̍k-pò」",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "愛參考氣象預報的嚴格定義",
    phioLim: "應討論",
    tsuLim: "「豪雨」是氣象專有名詞，有明確的定義，建議照用",
    phioGiam: "應討論",
    tsuGiam: "照漢字念",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo:
      "原則同意，「盡磅大水雨特報」建議改做「超磅大水雨特報 tshiau-pōng tuā-tsuí-hōo ti̍k-pò」",
  },
  {
    num: 93,
    huagi: "最低工資法",
    taigiHan: "上低工資法",
    taigiLo: "siōng-kē kang-tsu huat",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "最低工資法",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "法律名稱愛照字念",
    phioThiann: "應討論",
    tsuThiann: "最低工資法 tsuè kē kang-tsu-huat",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 94,
    huagi: "刷卡",
    taigiHan: "𫝻卡,鑢卡,觱卡",
    taigiLo: "huê-khah, lù-khah, pi-khah",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "𫝻卡",
    phioTsng: "應討論",
    tsuTsng: "鑢卡(信用卡)，觱卡(捷運，公車)",
    phioLim: "應討論",
    tsuLim: "我聽著的，若信用卡會講「鑢卡」，若坐車的卡會講「觱」。",
    phioGiam: "認同",
    tsuGiam: "鑢佮觱無仝",
    phioThiann: "認同",
    tsuThiann: "鑢卡 lù-khah；觱卡 pi-khah",
    phioHo: "認同",
    tsuHo: "看刷卡機器不同會當用無仝的動詞",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「鑢卡」、「觱卡」就好",
  },
  {
    num: 95,
    huagi: "收賄",
    taigiHan: "收烏西錢,收賄",
    taigiLo: "siu oo-se-tsînn,siu-hué",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "收烏西潛",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "收烏西錢袂䆀，嘛會當考慮「受烏西」。",
    phioGiam: "應討論",
    tsuGiam: "收紅包",
    phioThiann: "應討論",
    tsuThiann: "食錢 tsia̍h-tsînn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "口語講「收紅包siu âng-pau」、「食錢tsia̍h-tsînn」",
  },
  {
    num: 96,
    huagi: "打工換宿",
    taigiHan: "工作換蹛,做工換歇暝",
    taigiLo: "kang-tsok uānn-tuà,tsò-kang uānn hioh-mê",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "散工換蹛、作穡換蹛(t作穡的意思若像各地無啥一致，愛考慮）",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "用工拄蹛 iōng kang tú tuà",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "收「做工換蹛tsò/tsuè-kang uānn tuà」",
  },
  {
    num: 97,
    huagi: "熟客",
    taigiHan: "熟似客",
    taigiLo: "si̍k-sāi-kheh",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "主顧客",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "捷來客",
    phioGiam: "應討論",
    tsuGiam: "主顧客",
    phioThiann: "應討論",
    tsuThiann: "主顧客 tsú-kòo-kheh",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「熟似人客si̍k-sāi lâng-kheh」",
  },
  {
    num: 98,
    huagi: "匿蹤",
    taigiHan: "匿蹤",
    taigiLo: "li̍k-tsong",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "看前後文來決定",
    phioLim: "應討論",
    tsuLim: "建議莫收，看前後文",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "掩蹤 iám-tsong（案：台語有平行的構詞「掩身iám-sin」）",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "隱形",
    phioLoo: "應討論",
    tsuLoo: "建議改做「覕影bi̍h-iánn」",
  },
  {
    num: 99,
    huagi: "泳衣",
    taigiHan: "泅水衫",
    taigiLo: "siû-tsuí-sann",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "游泳衫",
    phioThiann: "應討論",
    tsuThiann: "游泳衫 iû-íng-sann",
    phioHo: "應討論",
    tsuHo: "也常聽有人說游泳衫",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 100,
    huagi: "宅經濟",
    taigiHan: "宅經濟",
    taigiLo: "the̍h-king-tsè",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "踮跤經濟",
    phioGiam: "認同",
    tsuGiam: "踮厝經濟",
    phioThiann: "應討論",
    tsuThiann:
      "居家經濟 ki-ka king-tsè / ku-ka king-tsè（案：「居家」《臺日》有收）",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「跔厝經濟 ku-tshù king-tsè」",
  },
  {
    num: 101,
    huagi: "網紅",
    taigiHan: "網衝,網紅,網路名人",
    taigiLo: "bāng-tsìng, bāng-âng, bāng-lōo bîng-jîn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "網衝",
    phioTsng: "認同",
    tsuTsng: "網紅",
    phioLim: "應討論",
    tsuLim: "「網衝」若像捷看人咧使用，毋知流通度有夠無",
    phioGiam: "認同",
    tsuGiam: "網衝",
    phioThiann: "應討論",
    tsuThiann:
      "網紅 bāng-âng；網路名人 bāng-lōo bîng-jîn（案：「網紅」權算是直接借。「衝 tshìng」字，有做動詞抑是形容詞的用法，總是，「XX衝」做名詞用，這款類型的構詞敢若較罕得看見。）",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "網紅",
    phioLoo: "應討論",
    tsuLoo:
      "「網路紅人 bāng-lōo âng-lâng」、「網紅 bāng-âng」、「網衝 bāng-tshìng」",
  },
  {
    num: 102,
    huagi: "帶風向",
    taigiHan: "帶風向",
    taigiLo: "tài-hong-hiòng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "𤆬風向",
    phioLim: "應討論",
    tsuLim: "酒",
    phioGiam: "應討論",
    tsuGiam: "引風勢（風向佮方向仝音歹分別）",
    phioThiann: "應討論",
    tsuThiann:
      "起風勢 khí-hōng-sè（案：台語的「起」也有「引𤆬」、「引起」、「指使」的意思，可比講：《教典》就有收「起人做歹 Khí lâng tsò-pháinn.」（教唆犯罪）。）",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「𤆬風頭 tshuā-hong-thâu」",
  },
  {
    num: 103,
    huagi: "大亨",
    taigiHan: "好額人",
    taigiLo: "hó-gia̍h-lâng",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "大好額人",
    phioTsng: "應討論",
    tsuTsng: "大好額人",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "無一定干焦好額",
    phioThiann: "應討論",
    tsuThiann:
      "大色人 tuā-sik-lâng（案：『大亨』，照講毋但「好額」爾，著愛有錢閣有勢）",
    phioHo: "應討論",
    tsuHo:
      '”大亨"毋若好額, 一般koh是某一个產業的成功經營者, 所以會當考慮共大亨翻作"(某一个產業的)頭人"',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「大好額人tuā hó-gia̍h-lâng」",
  },
  {
    num: 104,
    huagi: "游泳池",
    taigiHan: "泅水池",
    taigiLo: "siû-tsuí-tî",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "游泳池",
    phioThiann: "應討論",
    tsuThiann: "游泳池 iû-íng-tî",
    phioHo: "應討論",
    tsuHo: "也常聽有人說游泳池",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「游泳池iû-íng-tî」，真捷聽著，教典有收「游泳iû-íng」",
  },
  {
    num: 105,
    huagi: "立式划槳,立槳",
    taigiHan: "徛船,徛船扒,立槳",
    taigiLo: "khiā-tsûn, khiā-tsûn-pê, li̍p-tsiúnn",
    guagi: "SUP Stand Up Paddle",
    tsukai: "張日東老師提供的暫譯",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "立槳",
    phioLim: "應討論",
    tsuLim: "建議收徛式壓槳/徛式划船、徛槳。（台日ah攏用押，教典押、壓分用）",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "徛式划船 khiā-sik kò-tsûn",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "徛式划船",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「徛槳 khiā-tsiúnn」、「徛式划 khiā-sik kò」",
  },
  {
    num: 106,
    huagi: "機械手臂",
    taigiHan: "機械手股",
    taigiLo: "ki-hāi tshiú-kóo",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "手股干焦頂橛，手骨才是規肢？",
    phioGiam: "應討論",
    tsuGiam: "機械手",
    phioThiann: "應討論",
    tsuThiann: "機器手骨 ki-khì tshiú-kut",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "機械手",
    phioLoo: "應討論",
    tsuLoo: "建議收「機械手骨 ki-hāi tshiú-kut」",
  },
  {
    num: 107,
    huagi: "土撥鼠",
    taigiHan: "番鼠",
    taigiLo: "huan-tshí",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "掰塗膨鼠、鼢塗膨鼠",
    phioGiam: "認同",
    tsuGiam: "臺日：番鼠、竹鼠",
    phioThiann: "應討論",
    tsuThiann: "鼢塗鼠 bùn-thôo-tshí / bùn-thôo-tshú",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "掰塗鼠",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "bùn-tshú",
    phioLoo: "應討論",
    tsuLoo: "建議翻做「鼢塗膨鼠bùn-thôo-phòng-tshí/tshú」。",
  },
  {
    num: 108,
    huagi: "茶葉蛋",
    taigiHan: "茶葉蛋,茶滷卵",
    taigiLo: "tê-hio̍h-nn̄g,tê-lóo-nn̄g",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "茶滷卵",
    phioLim: "應討論",
    tsuLim: "茶米卵",
    phioGiam: "應討論",
    tsuGiam: "茶米卵",
    phioThiann: "應討論",
    tsuThiann: "茶米卵 tê-bí-nn̄g",
    phioHo: "應討論",
    tsuHo: "茶米滷蛋?",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "茶米卵",
    phioLoo: "應討論",
    tsuLoo: "建議「茶米卵 tê-bí-nn̄g」、「茶蛋 tê-tàn」",
  },
  {
    num: 109,
    huagi: "行人",
    taigiHan: "路人,過路人,行人",
    taigiLo: "lōo-lâng, kuè-lōo-lâng,hîng-jîn",
    guagi: "",
    tsukai: "相關詞彙：人行道",
    phioKhoo: "應討論",
    tsuKhoo: "行路人",
    phioTsng: "應討論",
    tsuTsng: "行路人",
    phioLim: "應討論",
    tsuLim: "建議收過路人就好",
    phioGiam: "應討論",
    tsuGiam: "直接講行人hîng-jîn",
    phioThiann: "認同",
    tsuThiann: "過路人 kuè-lōo-lâng / kè-lōo-lâng",
    phioHo: "應討論",
    tsuHo: '會當考慮直接翻"行人"就好',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "行路人",
    phioLoo: "應討論",
    tsuLoo: "建議講做「過路人kuè/kè-lōo-lâng」",
  },
  {
    num: 110,
    huagi: "果凍",
    taigiHan: "果凍, 水浸粿",
    taigiLo: "kó-tòng, tsuí-tsìm-kué",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "果凍",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "建議收「果凍kó-tàng」，果汁堅凍。嘛會使考慮收「凍果」，堅凍的果汁，通做台語佮華語構詞顛倒反的例。",
    phioGiam: "認同",
    tsuGiam: "kó-tàng",
    phioThiann: "應討論",
    tsuThiann: "菜燕 tshài-iàn",
    phioHo: "應討論",
    tsuHo: "會當討論看菜燕敢有適合",
    phioKueh: "應討論",
    tsuKueh: "雖講有方音差，毋過tàng敢若較捷聽",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "果凍",
    phioLoo: "應討論",
    tsuLoo: "建議收「果凍kó-tàng」",
  },
  {
    num: 111,
    huagi: "收回扣",
    taigiHan: "收回扣",
    taigiLo: "siu huê-khàu",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "commission",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "收khoo-mí-sióng",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "收khoo-mí-sióng",
    phioHo: "應討論",
    tsuHo: "提khoo-mi-siong?",
    phioKueh: "應討論",
    tsuKueh: "回收圈（khian）",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "收傭金",
    phioLoo: "應討論",
    tsuLoo: "一般聽著的是「收 khoo-mí-sióng」",
  },
  {
    num: 112,
    huagi: "栓塞",
    taigiHan: "栓窒,血角",
    taigiLo: "sng-that,hueh-kak",
    guagi: "",
    tsukai:
      "血管內的固體、液體或氣體團塊隨血流被運送到遠端並造成血流阻塞。慈濟醫院教學影片將「經動脈血管栓塞治療術」講做「經過動脈共血筋窒起來治療手術」 https://www.youtube.com/watch?v=h2sfaknHs-4&ab_channel=%E5%A4%A7%E6%9E%97%E6%85%88%E6%BF%9F%E9%86%AB%E9%99%A2%E6%95%99%E5%AD%B8%E7%A0%94%E7%99%BC%E7%B5%84",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "『栓』應該是取『瓶栓』的意思，用台語來描述這个詞是「像窒仔窒牢咧的狀態」。sng/tshng/tshuan攏是門栓仔的意思。",
    phioGiam: "應討論",
    tsuGiam: "窒血管",
    phioThiann: "應討論",
    tsuThiann: "窒that",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議照字講做「栓塞sng-sat」",
  },
  {
    num: 113,
    huagi: "追劇",
    taigiHan: "痟連續劇",
    taigiLo: "siáu liân-sio̍k-kio̍k",
    guagi: "",
    tsukai: "【台語聽有無】追劇追星相關台語按怎講",
    phioKhoo: "應討論",
    tsuKhoo: "追劇",
    phioTsng: "應討論",
    tsuTsng: "追劇，逐劇",
    phioLim: "應討論",
    tsuLim: "建議「追劇」就好",
    phioGiam: "應討論",
    tsuGiam: "追劇",
    phioThiann: "應討論",
    tsuThiann: "追劇 tui-kio̍k / tui-ki̍k",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "追劇",
    phioLoo: "應討論",
    tsuLoo: "建議直接照華語講做「追劇tui-kio̍k/ki̍k」",
  },
  {
    num: 114,
    huagi: "追星",
    taigiHan: "痟明星",
    taigiLo: "siáu bîng-tshenn",
    guagi: "",
    tsukai: "【台語聽有無】追劇追星相關台語按怎講",
    phioKhoo: "應討論",
    tsuKhoo: "逐明星",
    phioTsng: "應討論",
    tsuTsng: "追星，逐明星",
    phioLim: "應討論",
    tsuLim: "建議「追星」就好",
    phioGiam: "應討論",
    tsuGiam: "追星",
    phioThiann: "應討論",
    tsuThiann: "追星 tui-tshenn / tui-tshinn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議比照華語講做「追明星tui-bîng-tshenn/tshinn」",
  },
  {
    num: 115,
    huagi: "霧淞",
    taigiHan: "冰花",
    taigiLo: "ping-hue",
    guagi: "",
    tsukai:
      "霧凇，也稱樹掛或霧凍，是一種在天氣寒冷的地方出現的白色不透明晶體。",
    phioKhoo: "應討論",
    tsuKhoo: "霧淞",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "霧冰or霧霜 (https://www.moedict.tw/%E5%87%87)",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "凍霧 tàng-bū",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "有聽人講過「冰粉」",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「霧霜bū-sng」",
  },
  {
    num: 116,
    huagi: "半邊小臉症",
    taigiHan: "面大細䫌症",
    taigiLo: "bīn tuā-sè phué tsìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議「半爿細䫌症」",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "半爿細面症 puànn-pîng sè-bīn-tsìng",
    phioHo: "應討論",
    tsuHo: '加一個"症"讀起來敢若怪怪?',
    phioKueh: "應討論",
    tsuKueh: "半面麻痺？",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「䫌」補收「phé」的腔口差",
  },
  {
    num: 117,
    huagi: "級距、階層",
    taigiHan: "坎級",
    taigiLo: "khám-kip",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "華語是欲收佗一个？級距→級差kip-tsha，階層→階層kai-tsân",
    phioGiam: "應討論",
    tsuGiam: "gám",
    phioThiann: "應討論",
    tsuThiann: "坎 kám / gám",
    phioHo: "應討論",
    tsuHo: '看前後文, 有時直接用"坎"就好. 例如"一坎差幾分".',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "級數",
    phioSoo: "應討論",
    tsuSoo: "等級",
    phioLoo: "應討論",
    tsuLoo: "建議收「級差 kip-tsha」，「階層」佮「級距」意思無仝",
  },
  {
    num: 118,
    huagi: "打靶",
    taigiHan: "打靶",
    taigiLo: "tánn-pé",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "看軍中敢有台語講法",
    phioTsng: "應討論",
    tsuTsng: "參考軍隊的習慣用法",
    phioLim: "應討論",
    tsuLim: "建議用傳統詞「考銃」，若是箭就「考箭」，賰的類推。",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "考銃 khó-tshìng",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議改做「考銃訓練khó-tshìng hùn-liān」",
  },
  {
    num: 119,
    huagi: "沉浸式",
    taigiHan: "浸水式",
    taigiLo: "tsìm-tsuí-sik",
    guagi: "",
    tsukai: "沉浸式教學、沉浸式體驗",
    phioKhoo: "應討論",
    tsuKhoo: "沉浸式",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議用「沉浸式」就好",
    phioGiam: "應討論",
    tsuGiam: "浸潤式較好發音",
    phioThiann: "應討論",
    tsuThiann:
      "浸汰式tsìm-thuā-sik；沉浸式tîm-tsìm-sik（案：台語的「汰thuā」才有『受到他人或環境的影響而學習或改變』。「浸水」這款述賓的語義較具體，無合台語人的語感。）",
    phioHo: "應討論",
    tsuHo: "個人沒意見, 但常聽有人不贊同這種翻譯.",
    phioKueh: "應討論",
    tsuKueh: "沉浸式",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "全語境(教學)",
    phioLoo: "應討論",
    tsuLoo: "是抽象的概念，建議直接講做「沉浸式tîm-tsìm-sik」",
  },
  {
    num: 120,
    huagi: "面罩",
    taigiHan: "面罨",
    taigiLo: "bīn-am, bīn-om",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "「面罩bīn-tà」敢袂使？",
    phioGiam: "應討論",
    tsuGiam: "面罩",
    phioThiann: "應討論",
    tsuThiann: "面罩 bīn-tà / bīn-tàu",
    phioHo: "應討論",
    tsuHo: "常聽人說面罩",
    phioKueh: "應討論",
    tsuKueh: "語感感覺罩較大，像蠓罩",
    phioTshi: "應討論",
    tsuTshi: "面罩",
    phioSoo: "應討論",
    tsuSoo: "面罩",
    phioLoo: "應討論",
    tsuLoo: "建議收「面罩 bīn-tà」",
  },
];
