let uhuanikData = [
  {
    num: 1,
    huagi: "輝瑞",
    taigiHan: "輝瑞",
    taigiLo: "Hui-suī",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 2,
    huagi: "變異株",
    taigiHan: "變異株",
    taigiLo: "piàn-ī-tsu",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "piàn-ī-tsu / piàn-īnn-tsu",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 3,
    huagi: "聖嬰現象",
    taigiHan: "聖嬰現象",
    taigiLo: "Sìng-ing Hiān-siōng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "標音「Sìng-ing hiān-siōng」",
  },
  {
    num: 4,
    huagi: "羽絨衣",
    taigiHan: "羽絨衫",
    taigiLo: "ú-jiông-sann",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 5,
    huagi: "置身事外",
    taigiHan: "激外外",
    taigiLo: "kik-guā-guā",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 6,
    huagi: "鼻竇炎",
    taigiHan: "鼻竇炎",
    taigiLo: "phīnn-tōo-iām",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 7,
    huagi: "核分裂",
    taigiHan: "核分裂",
    taigiLo: "hi̍k-hun-lia̍t",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 8,
    huagi: "半衰期",
    taigiHan: "半衰期",
    taigiLo: "puàn-sue-kî.puànn-sue-kî",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 9,
    huagi: "起跑點",
    taigiHan: "起跑點",
    taigiLo: "khí-pháu-tiám",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 10,
    huagi: "監交",
    taigiHan: "監交",
    taigiLo: "kàm-kau",
    guagi: "",
    tsukai:
      "指監督前後任人員將職權與責任交接者。公務人員執行公務，為避免因交代不清，影響國家政務，故於辦理交接時，必須上級派員監督。依「公務人員交代條例」第7條規定：「機關首長交代時，應由該管上級機關派員監交；主管人員交代時，應由機關首長派員監交；經管人員交代時，應由機關首長派員會同該管主管人員監交。」",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 11,
    huagi: "積體電路",
    taigiHan: "積體電路",
    taigiLo: "tsik-thé tiān-lōo",
    guagi: "integrated circuit / IC",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "IC",
    phioLoo: "認同",
    tsuLoo: "標音改做「tsik-thé tiān-lōo」",
  },
  {
    num: 12,
    huagi: "森林火災",
    taigiHan: "火燒山",
    taigiLo: "hué sio suann",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "火燒樹林",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 13,
    huagi: "加熱菸",
    taigiHan: "加熱薰",
    taigiLo: "ka-jia̍t-hun",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "「共薰草炊予燒(無著火)的薰」，炊薰",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 14,
    huagi: "恆齒",
    taigiHan: "正齒,大人齒",
    taigiLo: "tsiànn-khí,tuā-lâng-khí",
    guagi: "",
    tsukai: "台華線頂對照典/林淑期",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 15,
    huagi: "傳播鏈",
    taigiHan: "傳播鍊",
    taigiLo: "thuân-pò-liān",
    guagi: "",
    tsukai: "台文應該寫「鏈」抑是「鍊」，有部份老師意見不同",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 16,
    huagi: "類普篩",
    taigiHan: "類普篩",
    taigiLo: "luī-phóo-thai",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 17,
    huagi: "猴痘",
    taigiHan: "猴珠",
    taigiLo: "kâu-tsu",
    guagi: "",
    tsukai:
      '天花(smallpox)是天珠，水痘(chickenpox)是水珠，推論猴痘(monkeypox)講"猴珠"。',
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 18,
    huagi: "貧窮線",
    taigiHan: "散赤線",
    taigiLo: "sàn-tshiah-suànn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 19,
    huagi: "核融合",
    taigiHan: "核融合",
    taigiLo: "hi̍k-iông-ha̍p",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 20,
    huagi: "燃料棒",
    taigiHan: "燃料棒",
    taigiLo: "jiân-liāu-pāng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "燒料枝sio-liāu-ki。燃料會當翻譯做「燒料」，「燃燒」是同義複詞，台語取「燒」，「O料」是常用構詞。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 21,
    huagi: "狐獴",
    taigiHan: "狐獴",
    taigiLo: "hô-bông",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 22,
    huagi: "加勒比海",
    taigiHan: "加勒比海",
    taigiLo: "Ka-li̍k-pí-hái",
    guagi: "Caribbean Sea",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "Caribbean Sea",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 23,
    huagi: "電競",
    taigiHan: "電競",
    taigiLo: "tiān-kīng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 24,
    huagi: "虛擬實況主",
    taigiHan: "虛擬實況主",
    taigiLo: "hi-gí si̍t-hóng-tsú",
    guagi: "VTuber",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 25,
    huagi: "宅配",
    taigiHan: "配送",
    taigiLo: "phuè-sàng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "配達",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 26,
    huagi: "憂鬱症",
    taigiHan: "憂鬱症",
    taigiLo: "iu-ut-tsìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: '也會當簡單講"鬱症"(列入第二推薦?)',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 27,
    huagi: "器官衰竭",
    taigiHan: "器官衰竭",
    taigiLo: "khì-kuan-sue-kia̍t",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "器官衰荏 khì-kuan sue-lám",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "khì-kuan sue-kia̍t",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "khì-kuan sue-kia̍t",
    phioTshi: "應討論",
    tsuTshi: "器官敗去",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "標音改做「khì-kuan sue-kia̍t」",
  },
  {
    num: 28,
    huagi: "負北極振盪",
    taigiHan: "負北極振盪",
    taigiLo: "Hū Pak-ki̍k tsín-tōng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "Hū-pak-ki̍k tsín-tōng",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "標音改做「hū Pa̍k-ki̍k tsín-tōng」",
  },
  {
    num: 29,
    huagi: "霹靂舞",
    taigiHan: "霹靂舞",
    taigiLo: "phik-li̍k-bú",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 30,
    huagi: "斷垣殘壁",
    taigiHan: "斷籬倒壁",
    taigiLo: "tn̄g-lî tó-piah",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "tn̄g-lî-tó-piah",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "羅馬字愛連寫「tn̄g-lî-tó-piah」",
  },
  {
    num: 31,
    huagi: "擔架",
    taigiHan: "軟轎",
    taigiLo: "nńg-kiō",
    guagi: "",
    tsukai: "消防人員",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "軟床 nńg-tshn̂g",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam:
      '床椅 tshn̂g-í (Macgowan1883 "English and Chinese dictionary of the Amoy dialect")',
    phioThiann: "認同",
    tsuThiann: "軟床 nńg-tshn̂g",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 32,
    huagi: "前瞻",
    taigiHan: "前瞻",
    taigiLo: "tsiân-tsiam",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "若是「前瞻性」的前瞻，建議莫收，看前後文，意思是有未來。若是「前瞻計畫」的前瞻，建議收完整的「前瞻計畫」",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "標音改做「tsiân-tsiam」",
  },
  {
    num: 33,
    huagi: "塔利班",
    taigiHan: "塔利班",
    taigiLo: "Thap-lī-pan",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "Thah-lī-pan",
    phioGiam: "認同",
    tsuGiam: "音 Thah-lī-pan",
    phioThiann: "認同",
    tsuThiann: "Thah-lī-pan",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "Thah-lī-pan",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議標音改做「Thah-lī-pan」",
  },
  {
    num: 34,
    huagi: "膳食纖維",
    taigiHan: "膳食纖維",
    taigiLo: "Siān-si̍t-tshiam-uî",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "食食纖維tsia̍h-si̍t-tshiam-uî",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "食食纖維 tsia̍h-si̍t tshiam-uî",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "Siān-si̍t tshiam-uî",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "食物纖維",
    phioLoo: "應討論",
    tsuLoo: "建議改做「食食纖維tsia̍h-si̍t tshiam-uî」",
  },
  {
    num: 35,
    huagi: "梅花座",
    taigiHan: "閬位坐",
    taigiLo: "làng-uī-tsē",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "muî-hua-tsō",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "muî-hue-tsō",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "梅花座",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 36,
    huagi: "宿醉",
    taigiHan: "隔暝醉",
    taigiLo: "keh-mê tsuì",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "宿醉 siok-tsuì《臺日》",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 37,
    huagi: "良莠不齊",
    taigiHan: "好䆀無齊勻",
    taigiLo: "hó-bái bô tsiâu-ûn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "三不等 sam-put-tíng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 38,
    huagi: "以身試法",
    taigiHan: "用頭毛試火",
    taigiLo: "iōng thâu-moo tshì hué",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "以身試法",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "頭毛試火 thâu-mn̂g tshì hué",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 39,
    huagi: "不對稱作戰能力",
    taigiHan: "無對等作戰能力",
    taigiLo: "bô-tuì-tíng tsok-tsiàn lîng-li̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 40,
    huagi: "安全帽顎杯",
    taigiHan: "下頦觳仔",
    taigiLo: "ē-hâi-khok-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "安全帽下頦觳。「安全帽」應該袂當省略？",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 41,
    huagi: "天花",
    taigiHan: "天珠",
    taigiLo: "thian-tsu",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "珠，出珠",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "出珠 tshut-tsu",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 42,
    huagi: "肥胖症",
    taigiHan: "大箍症",
    taigiLo: "tuā-khoo-tsìng",
    guagi: "",
    tsukai: "相關詞彙：肥胖問題、肥胖機率、肥胖",
    phioKhoo: "應討論",
    tsuKhoo: "肥滿症",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「超重症tshiau-tāng-tsǹg」",
  },
  {
    num: 43,
    huagi: "勗勉",
    taigiHan: "勗勉",
    taigiLo: "hiok-bián",
    guagi: "",
    tsukai: "漢字音是甘字典讀音，教典無收",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "建議收勗勉典禮，當做專有名詞。若毋是指典禮，講勉勵就好。（辭典：勗勉：勉勵）",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「嘉勉ka-bián」",
  },
  {
    num: 44,
    huagi: "車輛出軌",
    taigiHan: "敗馬",
    taigiLo: "pāi-bé",
    guagi: "",
    tsukai: "台日大辭典/教育部台語辭典",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "華語改「火車出軌」，台語對「火車敗馬」，火車會當改別款車，捷運敗馬、高鐵敗馬",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "敗馬pāi-bé / 敗輦 pāi-lián",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "敗馬、敗輦(pāi-lián)、火車跋落馬",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「列車敗馬lia̍t-tshia pāi-bé」",
  },
  {
    num: 45,
    huagi: "齒輪",
    taigiHan: "齒仔",
    taigiLo: "khí-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "齒lián",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "gí-á",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "齒輪",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 46,
    huagi: "紐蛋白",
    taigiHan: "紐卵白",
    taigiLo: "liú-nn̄g-pe̍h",
    guagi: "vinculin",
    tsukai: "Vinculin - Wikipedia",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "Vinculin，共細胞連起來的卵白，華語翻譯可能取「樞紐」抑是「紐扣」的意思，若共解說做若像鈕仔的作用仝款嘛會通，毋過咱是用「鈕」毋是用「紐」。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 47,
    huagi: "羊駝",
    taigiHan: "羊駱駝",
    taigiLo: "iûnn-lo̍k-tô",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "羊駝iûnn-tô就好？",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "羊駝 iûnn-tô",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "iûnn-tô",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "羊駝",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 48,
    huagi: "侵蝕",
    taigiHan: "侵蝕",
    taigiLo: "tshim-si̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "si̍t，教典「蝕」共si̍t列做俗音應該是錯誤，這字是「職」韻，-t尾無毋著，台日典、甘字典攏收si̍t，顛倒無si̍k",
    phioGiam: "認同",
    tsuGiam: "羅馬字應該是 tshim-si̍t",
    phioThiann: "認同",
    tsuThiann: "tshim-si̍t / tshim-si̍k",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "蛀（tsiù）",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 49,
    huagi: "麥當勞",
    taigiHan: "麥當勞",
    taigiLo: "Be̍h-tong-lô",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "Mcdonalds",
    phioLim: "認同",
    tsuLim: "Be̍h-tong-lô",
    phioGiam: "應討論",
    tsuGiam: "音 Bi̍k-tong-lô",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議標音改做「Bi̍k-tong-lô」",
  },
  {
    num: 50,
    huagi: "方尖碑",
    taigiHan: "方尖碑",
    taigiLo: "png-tsiam-pi",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "四角尖碑",
    phioGiam: "應討論",
    tsuGiam: "音 hong-tsiam-pi",
    phioThiann: "認同",
    tsuThiann: "hong-tsiam-pi",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議標音改做「hong-tsiam-pi」",
  },
  {
    num: 51,
    huagi: "奢侈品",
    taigiHan: "奢侈品",
    taigiLo: "tshia-tshí-phín",
    guagi: "",
    tsukai: "",
    phioKhoo: "",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "奢華品tshia-hua-phín、奢華物",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "奢華物 tshia-hua-mi̍h",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 52,
    huagi: "抓舉",
    taigiHan: "掠夯",
    taigiLo: "lia̍h-giâ",
    guagi: "snatch",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "反對",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 53,
    huagi: "斑馬線",
    taigiHan: "斑馬線",
    taigiLo: "pan-má-suànn,pan-bé-suànn",
    guagi: "",
    tsukai: "教典收錄",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "反對",
    tsuTsng: "重複",
    phioLim: "應討論",
    tsuLim: "pan-bé-suànn就好",
    phioGiam: "應討論",
    tsuGiam: "pan-bé-suànn",
    phioThiann: "反對",
    tsuThiann: "重複",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「斑馬線pan-bé-suànn」",
  },
  {
    num: 54,
    huagi: "鑿花/細部雕刻",
    taigiHan: "鑿花",
    taigiLo: "tsha̍k-hue",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "先確定意思",
    phioLim: "應討論",
    tsuLim: "華語意思先確定，兩个無啥仝款",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "刻花 khik-hue",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "剪窗花（tsián-thang-hue）",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「雕花tiau-hue」、「刻花khik-hue」選一个",
  },
  {
    num: 55,
    huagi: "夾腳拖、人字拖",
    taigiHan: "䇭履仔",
    taigiLo: "ló-lí-á",
    guagi: "",
    tsukai: "iTaigi華台對照典",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "鋏指頭仔拖、人字淺拖？",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "人字拖仔 lâng--jī thua-á",
    phioHo: "應討論",
    tsuHo: '也定聽著"su-lit-pah"的講法',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「夾跤淺拖ngeh-kha tshián-thua」",
  },
  {
    num: 56,
    huagi: "隱形缺氧",
    taigiHan: "隱形無氣",
    taigiLo: "ún-hîng bô-khuì",
    guagi: "Silent Hypoxia",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "隱形欠氣、隱形欠氧",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "隱形缺氧ún-hîng khuat-ióng / 快樂缺氧 khuài-lo̍k khuat-ióng",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 57,
    huagi: "標靶藥物",
    taigiHan: "標靶藥仔",
    taigiLo: "piau-pé io̍h-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "藥物就好，免改仔？",
    phioGiam: "應討論",
    tsuGiam: "「藥物」毋免講做「藥仔」",
    phioThiann: "應討論",
    tsuThiann: "標靶藥物 piau-pé io̍h-bu̍t",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "專用藥",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "標音改做「piau-pé io̍h-á」",
  },
  {
    num: 58,
    huagi: "帳棚",
    taigiHan: "布篷",
    taigiLo: "pòo-phâng",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "布篷厝",
    phioLim: "應討論",
    tsuLim: "布篷厝，用布篷搭的厝。對比：草厝",
    phioGiam: "反對",
    tsuGiam: "布棚pòo-pînn/pòo-pênn(教育部)",
    phioThiann: "認同",
    tsuThiann: "布棚 pòo-pênn / pòo-pînn ；抑是 thiàn-tooh",
    phioHo: "應討論",
    tsuHo: '也定聽人用"thiàn-tòo"',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 59,
    huagi: "三角錐",
    taigiHan: "交通筍",
    taigiLo: "kau-thong-sún",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "三角錐 sann-kak-tsui",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議照字講做「三角錐sann-kak-tsui」",
  },
  {
    num: 60,
    huagi: "通貨膨脹",
    taigiHan: "通貨膨脹",
    taigiLo: "thong-huè-phòng-tiòng",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "通貨膨大",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "通貨膨脹、通貨冗剩",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "錢變薄tsînn piàn po̍h / 通膨 thong-phîng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 61,
    huagi: "梯田",
    taigiHan: "層田,山田,內山田,山頂田,重坎田,坪仔田,埒仔田,石埒仔田",
    taigiLo:
      "tsân-tshân,suann-tshân,lāi-suann-tshân,suann-tíng-tshân,tîng-khám-tshân,phiânn-á-tshân,lua̍h-á-tshân,tsio̍h-lua̍h-á-tshân",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議收兩个就好(山田、捋仔田)",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann:
      "埒仔田lua̍h-á-tshân / 坪仔田phiânn- á-tshân / 內山田 lāi-suann-tshân",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "thui-tshân",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "埒仔田",
    phioLoo: "應討論",
    tsuLoo: "建議收「坪仔田phiânn-á-tshân」抑是「埒仔田lua̍h-á-tshân」",
  },
  {
    num: 62,
    huagi: "碾米廠",
    taigiHan: "米絞仔",
    taigiLo: "bí-ká-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "塗礱間",
    phioTsng: "應討論",
    tsuTsng: "毋免「仔」",
    phioLim: "應討論",
    tsuLim: "米絞，應該無仔",
    phioGiam: "應討論",
    tsuGiam: "毋免「仔」",
    phioThiann: "認同",
    tsuThiann: "米絞 bí-ká",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "米絞",
    phioLoo: "應討論",
    tsuLoo: "在來講做「米絞bí-ká」",
  },
  {
    num: 63,
    huagi: "肇事逃逸",
    taigiHan: "肇事逃逸",
    taigiLo: "Tiāu-sū-tô-i̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "反對",
    tsuLim: "這條刪除，頭前已經有",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "出事遛走 tshut-sū liù-tsáu / 出事僻走 tshut-sū phiah-tsáu",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「事故偷旋sū-kòo thau suan」",
  },
  {
    num: 64,
    huagi: "油壓剪",
    taigiHan: "大鐵剪",
    taigiLo: "tuā-thih-tsián",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "反對",
    tsuLim: "油壓剪iû-ap-tsián",
    phioGiam: "應討論",
    tsuGiam: "照漢字「油壓剪」iû-ap-tsián",
    phioThiann: "應討論",
    tsuThiann: "油壓剪 iû-ap-tsián",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "反對",
    tsuTshi: "油壓剪",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "直接講做「油壓剪iû-ap-tsián」",
  },
  {
    num: 65,
    huagi: "預售屋",
    taigiHan: "預售厝",
    taigiLo: "ī-siū-tshù",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "預賣厝",
    phioTsng: "應討論",
    tsuTsng: "預賣厝",
    phioLim: "應討論",
    tsuLim: "預販厝？（佮販厝對應）",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: '會當考慮用預售"屋"就好',
    phioKueh: "應討論",
    tsuKueh: "先賣才起的厝",
    phioTshi: "應討論",
    tsuTshi: "販厝",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 66,
    huagi: "駭客",
    taigiHan: "械客",
    taigiLo: "hāi-kheh",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "駭客hái-kheh，甘字典、彙音寶鑑有收「駭」字",
    phioGiam: "應討論",
    tsuGiam: "駭客 hái-kheh",
    phioThiann: "應討論",
    tsuThiann: "駭客 hái-kheh",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "害客（hāi-kheh）",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "害客",
    phioLoo: "認同",
    tsuLoo: "標音改做「hái-kheh」",
  },
  {
    num: 67,
    huagi: "三角錐",
    taigiHan: "塑膠筍,紅龜,路閘",
    taigiLo: "sok-ka-sún/âng-ku/lōo-tsa̍h",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "反對",
    tsuLim: "這條刪除，頭前已經有「交通筍」",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "反對",
    tsuThiann: "重複",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議照字講做「三角錐sann-kak-tsui」",
  },
  {
    num: 68,
    huagi: "手扶梯",
    taigiHan: "電樓梯",
    taigiLo: "tiān-lâu-thui",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "手扶梯 or 電扶梯?",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "電梯、電樓梯",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "扞梯 huānn-thui / 電扶梯 tiān-hû-thui",
    phioHo: "應討論",
    tsuHo: '有聽過用"電梯"和"流籠"來區分"電扶梯"和"電梯"的',
    phioKueh: "應討論",
    tsuKueh: "手扶電梯",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "手扶梯",
    phioLoo: "應討論",
    tsuLoo: "建議講做「手扞梯tshiú-huānn-thui」",
  },
  {
    num: 69,
    huagi: "肇事逃逸",
    taigiHan: "肇事逃走",
    taigiLo: "tiāu-sū tô-tsáu",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "起事逃走。雖然「起事」是指惹是非，毋過華語的「肇」嘛是引起的意思。「肇事」建議佇法律名詞才使用。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "反對",
    tsuThiann: "重複",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「事故偷旋sū-kòo thau suan」",
  },
  {
    num: 70,
    huagi: "情緒勒索",
    taigiHan: "感情威脅/刐感情/用情份共人刁",
    taigiLo: "kám-tsîng ui-hia̍p／táinn kám-tsîng／iōng tsîng-hūn kā lâng tiau",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "感情威脅",
    phioTsng: "應討論",
    tsuTsng: "情感綁票",
    phioLim: "應討論",
    tsuLim: "摃人情緒。縛人情感（情感綁架）",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "情緒叨撚 tsîng-sū lo-lián",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「撒體威脅sāi-thái ui-hia̍p」",
  },
  {
    num: 71,
    huagi: "疲於奔命",
    taigiHan: "硞硞傱",
    taigiLo: "kho̍k-kho̍k-tsông",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "硞硞傱無一定有「疲」的意思。傱甲忝忝、走甲牚腿(邱)",
    phioGiam: "應討論",
    tsuGiam: "四字成語照漢字念 phî-û-phun-bīng",
    phioThiann: "應討論",
    tsuThiann: "捙跋反tshia-pua̍h-píng",
    phioHo: "應討論",
    tsuHo: "意思無啥相siāng",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "會當考慮「捙跋反tshia-pua̍h-píng」",
  },
  {
    num: 72,
    huagi: "掣肘",
    taigiHan: "縛跤縛手",
    taigiLo: "pa̍k kha pa̍k tshiú",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "搝後跤 giú-āu-kha",
    phioLim: "應討論",
    tsuLim: "建議莫收，愛看頂下文，無適合直接詞對詞",
    phioGiam: "應討論",
    tsuGiam: "阻礙tsóo-gāi",
    phioThiann: "應討論",
    tsuThiann: "掠跤掠手 lia̍h-kha-lia̍h-tshiú",
    phioHo: "應討論",
    tsuHo:
      '掣肘是"對別人", "縛跤縛手"是家己感覺, 無啥相siāng, 會當討論看敢有欲翻作"搝衫搝褲"(笑).',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo:
      "建議講做「掠跤掠手lia̍h-kha-lia̍h-tshiú」抑是「纏跤絆手tînn-kha-puànn-tshiú」",
  },
  {
    num: 73,
    huagi: "隔空交火",
    taigiHan: "空中對喝",
    taigiLo: "khong-tiong tuì huah",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "對唱tuì-tshiàng",
    phioLim: "反對",
    tsuLim: "線頂對唱suànn-tíng-tuì-tshiàng",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "隔馬對削keh-bé tuì-siah",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「對喝」建議改做「對唱tuì-tshiàng」",
  },
  {
    num: 74,
    huagi: "泡泡紙",
    taigiHan: "泡泡紙",
    taigiLo: "phok-phok-tsuá",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "字音無對應",
    phioTsng: "應討論",
    tsuTsng: "噗仔紙pho̍k-á-tsuá",
    phioLim: "反對",
    tsuLim: "噗仔紙pho̍k-á-tsuá",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "噗仔紙 phok-á-tsuá",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「噗仔紙phok-á-tsuá」",
  },
  {
    num: 75,
    huagi: "打炒房",
    taigiHan: "打炒房",
    taigiLo: "tánn-tshá-pâng",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "壓厝價 ah tshù-kè",
    phioLim: "應討論",
    tsuLim: "炒房：夯厝價。打炒房：壓厝價？",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "壓厝價 ah tshù-kè",
    phioHo: "應討論",
    tsuHo: '華語的動詞用"打", 台語會當考慮用壓(ah); 壓房地產',
    phioKueh: "應討論",
    tsuKueh: "押炒抐厝價",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 76,
    huagi: "抓舉",
    taigiHan: "掠舉",
    taigiLo: "lia̍h-kí",
    guagi: "snatch",
    tsukai: "",
    phioKhoo: "反對",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "反對",
    tsuLim: "這條刪除，頭前已經有「掠夯」",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "反對",
    tsuThiann: "重複",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「掠夯」",
  },
  {
    num: 77,
    huagi: "挺舉",
    taigiHan: "挺舉",
    taigiLo: "thíng-kí",
    guagi: "clean and jerk",
    tsukai: "",
    phioKhoo: "反對",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "反對",
    tsuLim: "這條刪除，用下面的牚夯thènn-giâ",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "反對",
    tsuThiann: "重複",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「牚夯thènn/thìnn-giâ」",
  },
  {
    num: 78,
    huagi: "挺舉",
    taigiHan: "撐夯",
    taigiLo: "thenn-giâ",
    guagi: "clean and jerk",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "牚夯thènn-giâ",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "牚夯 thènn-giâ / thìnn-giâ",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "反對",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「牚夯thènn/thìnn-giâ」",
  },
  {
    num: 79,
    huagi: "蒸餾",
    taigiHan: "激造",
    taigiLo: "kik-tsō",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "臺日「蒸溜水」tsing-liû",
    phioThiann: "應討論",
    tsuThiann: "tsing-liû",
    phioHo: "應討論",
    tsuHo: "蒸餾有真濟用法(水/酒...)愛看規段.",
    phioKueh: "應討論",
    tsuKueh: "thing-liû（台日有收）",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "蒸餾",
    phioLoo: "應討論",
    tsuLoo: "建議照字唸做「tsing-liû」",
  },
  {
    num: 80,
    huagi: "懸浮粒子",
    taigiHan: "風飛坱埃",
    taigiLo: "hong-pue ing-ia",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "坱埃粒子ing-ia-lia̍p-tsú？",
    phioGiam: "應討論",
    tsuGiam: "懸浮幼粒 hiân-phû iù-lia̍p",
    phioThiann: "應討論",
    tsuThiann: "幼浮塗粉 iù phû thôo-hún / 幼浮塵 iù phû-tîn",
    phioHo: "應討論",
    tsuHo: "懸浮粒子",
    phioKueh: "應討論",
    tsuKueh: "垃圾幼粒仔（lah-sap iù-lia̍p-á）",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 81,
    huagi: "鱘魚/鱘龍魚",
    taigiHan: "鱘魚",
    taigiLo: "tsîm-hî",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議華語收「鱘龍魚」就好。台語sîm-liông-hî",
    phioGiam: "應討論",
    tsuGiam:
      '音 sîm-liông-hî (Macgowan1883 "English and Chinese dictionary of the Amoy dialect")',
    phioThiann: "應討論",
    tsuThiann: "鱘龍魚 sîm-liông-hî",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "龍魚、活化石魚",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "補標音「sîm(-liông)-hî/hû」",
  },
  {
    num: 82,
    huagi: "葉克膜",
    taigiHan: "葉克膜",
    taigiLo: "Ia̍p-khik-bo̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "É khuh mòo 字音無對應",
    phioTsng: "應討論",
    tsuTsng: "É khuh mòo",
    phioLim: "應討論",
    tsuLim: "ECMO，葉克膜Ē-khik-mo̍oh",
    phioGiam: "應討論",
    tsuGiam: "「膜」音mo̍oh",
    phioThiann: "應討論",
    tsuThiann: "ia̍p-khik-mo̍oh",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "ia̍p-khik-bo̍k",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議標音改做「ia̍p-khik-mo̍oh」",
  },
  {
    num: 83,
    huagi: "彈匣",
    taigiHan: "銃子盒仔",
    taigiLo: "tshìng-tsí a̍p-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "khueh-á /kheh-á",
    phioLim: "反對",
    tsuLim: "銃子篋仔tshìng-tsí-kheh-á",
    phioGiam: "應討論",
    tsuGiam: "銃子篋仔 khueh-á /kheh-á",
    phioThiann: "應討論",
    tsuThiann: "銃子篋仔 tshìng-tsí-kheh-á",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "銃子篋仔",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「銃子篋仔tshìng-tsí-kheh-á」",
  },
  {
    num: 84,
    huagi: "刺槍術",
    taigiHan: "鑿銃術",
    taigiLo: "tsha̍k-tshìng-su̍t",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "刺馬刀術",
    phioLim: "應討論",
    tsuLim: "銃尾刀術tshìng-bué-to-su̍t。台日有收「銃尾刀」",
    phioGiam: "應討論",
    tsuGiam: "tshìng or tshiunn?",
    phioThiann: "應討論",
    tsuThiann: "銃尾刀術 tshìng-bué-to-su̍t",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "戮銃術",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "反對",
    tsuLoo: "建議講做「揬銃術tu̍h-tshìng-su̍t」",
  },
  {
    num: 85,
    huagi: "軍閥",
    taigiHan: "𤆬兵的",
    taigiLo: "tshuā-ping--ê",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "kun-hua̍t",
    phioLim: "應討論",
    tsuLim: "kun-hua̍t",
    phioGiam: "應討論",
    tsuGiam: "照漢字",
    phioThiann: "認同",
    tsuThiann: "軍閥 kun-hua̍t",
    phioHo: "應討論",
    tsuHo: '會當考慮直接講"軍閥"(kun-hua̍t)就好.',
    phioKueh: "應討論",
    tsuKueh: "kun-hua̍t",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議照字唸做「kun-hua̍t」",
  },
  {
    num: 86,
    huagi: "斑馬線",
    taigiHan: "過路線",
    taigiLo: "kuè-lōo-suànn",
    guagi: "",
    tsukai: "",
    phioKhoo: "反對",
    tsuKhoo: "斑馬線",
    phioTsng: "反對",
    tsuTsng: "斑馬線",
    phioLim: "反對",
    tsuLim: "這條刪除，頭前已經有「斑馬線」pan-bé-suànn",
    phioGiam: "應討論",
    tsuGiam: "照漢字 pan-bé-suànn",
    phioThiann: "應討論",
    tsuThiann: "斑馬線 pan-má-suànn / pan-bé-suànn",
    phioHo: "應討論",
    tsuHo: '小學課本kan-na叫做"斑馬線", 會當考慮直接採用',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "反對",
    tsuTshi: "斑馬線",
    phioSoo: "",
    tsuSoo: "斑馬線",
    phioLoo: "應討論",
    tsuLoo: "得直接講做「斑馬線pan-bé-suànn」",
  },
  {
    num: 87,
    huagi: "吹哨者",
    taigiHan: "搤空者",
    taigiLo: "iah-khang-tsiá",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "揭弊者 khiat-pè-tsiá /告發者",
    phioThiann: "應討論",
    tsuThiann: "掠縫者lia̍h-phāng-tsiá",
    phioHo: "應討論",
    tsuHo: '搤空khah負面; 吹哨是正面, 建議直接翻作"歕觱者"這類的用法',
    phioKueh: "應討論",
    tsuKueh: "抓耙仔（jiàu/liàu-pê-á）",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「通報者thong-pò-tsiá抑是「歕觱仔的pûn-pi-á--ê」",
  },
  {
    num: 88,
    huagi: "擺爛",
    taigiHan: "激爛",
    taigiLo: "ki̍k-nuā",
    guagi: "",
    tsukai: "",
    phioKhoo: "反對",
    tsuKhoo: "放外外",
    phioTsng: "反對",
    tsuTsng: "放外外or放懶懶",
    phioLim: "應討論",
    tsuLim: "放予爛？",
    phioGiam: "應討論",
    tsuGiam: "放予爛",
    phioThiann: "應討論",
    tsuThiann: "放予爛 pàng hōo nuā",
    phioHo: "應討論",
    tsuHo: "愛看前後文",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "放予爛",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「放予爛pàng hōo nuā」",
  },
  {
    num: 89,
    huagi: "針織",
    taigiHan: "刺膨紗",
    taigiLo: "tshiah phòng-se",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "刺紗",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "反對",
    tsuLim:
      "「針織」毋是干焦刺膨紗，用鉤針來織，應該會當直接講「針織」。華語嘛會當考慮改收「針織衫」。",
    phioGiam: "應討論",
    tsuGiam: "照漢字「針織」tsiam-tsit",
    phioThiann: "應討論",
    tsuThiann: "針織 tsiam-tsit",
    phioHo: "應討論",
    tsuHo: "針織衫",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "反對",
    tsuTshi: "針織",
    phioSoo: "",
    tsuSoo: "針織",
    phioLoo: "應討論",
    tsuLoo: "直接講做「針織tsiam-tsit」",
  },
  {
    num: 90,
    huagi: "住宿",
    taigiHan: "蹛宿",
    taigiLo: "tuà-siok",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "過暗",
    phioTsng: "應討論",
    tsuTsng: "過暝",
    phioLim: "應討論",
    tsuLim:
      "蹛or歇暝。（比論講：住宿或休息？→蹛/歇暝抑是歇睏？住宿附早餐→蹛/歇暝佮早頓",
    phioGiam: "應討論",
    tsuGiam: "歇暝 hioh-mî /歇暗 hioh-àm /蹛暝 tuà-mî",
    phioThiann: "應討論",
    tsuThiann: "歇暝 hioh-mê / 蹛暝 tuà-mê",
    phioHo: "應討論",
    tsuHo: '會當考慮直接用"蹛暝"就好.',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「歇暝hioh-mê/mî」",
  },
  {
    num: 91,
    huagi: "刺槍術",
    taigiHan: "刺銃術",
    taigiLo: "tshì-tshìng-su̍t",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "反對",
    tsuLim: "這條刪除，頭前已經有",
    phioGiam: "應討論",
    tsuGiam: "tshìng or tshiunn?",
    phioThiann: "",
    tsuThiann: "重複",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「揬銃術tu̍h-tshìng-su̍t」",
  },
  {
    num: 92,
    huagi: "刺槍術",
    taigiHan: "銃劍術",
    taigiLo: "tshìng-kiàm-su̍t",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "反對",
    tsuLim: "這條刪除，頭前已經有",
    phioGiam: "應討論",
    tsuGiam: "tshìng or tshiunn?",
    phioThiann: "",
    tsuThiann: "重複",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "反對",
    tsuLoo: "建議講做「揬銃術tu̍h-tshìng-su̍t」",
  },
  {
    num: 93,
    huagi: "攔截",
    taigiHan: "攔截",
    taigiLo: "nuâ-tsia̍t",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "接閘",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "攔閘nuâ-tsa̍h",
    phioGiam: "應討論",
    tsuGiam: "攔閘 nâ-tsa̍h /nuâ-tsa̍h",
    phioThiann: "應討論",
    tsuThiann: "攔閘 nuâ-tsa̍h / nâ-tsa̍h",
    phioHo: "應討論",
    tsuHo: '傳統有"攔閘"會用法, 會當直接提來用',
    phioKueh: "應討論",
    tsuKueh: "nuâ-tsa̍h（台日有收）",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議改做「攔閘nuâ-tsa̍h」",
  },
  {
    num: 94,
    huagi: "偶像",
    taigiHan: "煞心明星",
    taigiLo: "sannh-sim bîng-tshenn,sannh-sim bîng-tshinn",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "唸ái-toh(字音無對應)",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "偶像無一定是明星。ngóo-siōng",
    phioGiam: "應討論",
    tsuGiam: "偶像 ngóo-siōng",
    phioThiann: "應討論",
    tsuThiann: "偶像 ngóo-siōng",
    phioHo: "應討論",
    tsuHo: '用"ái-toh”就好?',
    phioKueh: "應討論",
    tsuKueh: "煞心人（sannh-sim-lâng）",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「煞心」無做形容詞的用法，建議照字講做「偶像ngóo-siōng」",
  },
  {
    num: 95,
    huagi: "停滯性通膨",
    taigiHan: "死水通貨冗剩",
    taigiLo: "sí-tsuí thong-huè liōng-siōng",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "建議華語收完整的「停滯性通貨膨脹」，頭前通貨膨脹的決議遮愛照用。「停滯性」建議翻做「擋定性tòng-tiānn-sìng」",
    phioGiam: "應討論",
    tsuGiam: "死水性通貨膨大",
    phioThiann: "應討論",
    tsuThiann: "停滯性通膨 thîng-tù-sìng thong-phîng",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "停滯通貨冗剩（thîng-tù thong-huè liōng-siōng）",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「擋恬性通膨tòng-tiām-sìng thong-phòng」",
  },
  {
    num: 96,
    huagi: "通貨膨脹",
    taigiHan: "冇殼經濟",
    taigiLo: "phànn-khak king-tsè",
    guagi: "",
    tsukai: "",
    phioKhoo: "反對",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "反對",
    tsuLim: "這條刪除，頭前已經有",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "反對",
    tsuThiann: "重複",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "直接講做「thong-huè-phòng-tiòng」",
  },
  {
    num: 97,
    huagi: "航線",
    taigiHan: "水路",
    taigiLo: "tsuí-lōo",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "hâng-suànn",
    phioLim: "應討論",
    tsuLim: "hâng-suànn",
    phioGiam: "應討論",
    tsuGiam: "hâng-suànn",
    phioThiann: "應討論",
    tsuThiann: "航線 hâng-suànn",
    phioHo: "應討論",
    tsuHo: '航線有"船/飛行機"2種. 所以會當考慮直接用"航線"就好',
    phioKueh: "應討論",
    tsuKueh: "愛看是講飛機的「航線」抑是船的「水路」",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "航線",
    phioLoo: "應討論",
    tsuLoo: "建議直接講做「航線hâng-suànn」",
  },
  {
    num: 98,
    huagi: "斑馬線",
    taigiHan: "馬條線",
    taigiLo: "bé-tiâu-suànn",
    guagi: "",
    tsukai: "",
    phioKhoo: "反對",
    tsuKhoo: "",
    phioTsng: "反對",
    tsuTsng: "重複",
    phioLim: "反對",
    tsuLim: "這條刪除，頭前已經有",
    phioGiam: "應討論",
    tsuGiam: "斑馬線",
    phioThiann: "反對",
    tsuThiann: "重複",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "",
    phioTshi: "反對",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議講做「斑馬線pan-bé-suànn」",
  },
  {
    num: 99,
    huagi: "積極",
    taigiHan: "猛捷",
    taigiLo: "mé-tsia̍p",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "反對",
    tsuTsng: "tsik-ki̍k",
    phioLim: "反對",
    tsuLim: "這條建議莫收。若欲收直接講積極tsik-ki̍k就好。",
    phioGiam: "應討論",
    tsuGiam: "照漢字tsik-ki̍k",
    phioThiann: "應討論",
    tsuThiann: "積極 tsik-ki̍k",
    phioHo: "應討論",
    tsuHo: "愛看前後文",
    phioKueh: "應討論",
    tsuKueh: "tsik-ki̍k台日、教典有收",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "",
    tsuSoo: "積極",
    phioLoo: "應討論",
    tsuLoo: "建議照字講做「積極tsik-ki̍k」",
  },
];
