let uhuanikData = [
  {
    "num": 1,
    "huagi": "明太子",
    "taigiHan": "明太子",
    "taigiLo": "bîng-thài-tsú",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "應討論",
    "tsuTsng": "建議直接用日語發音",
    "phioLim": "認同",
    "tsuLim": "",
    "phioGiam": "應討論",
    "tsuGiam": "bîng-thài tsí（意思是「明太」的子）",
    "phioThiann": "認同",
    "tsuThiann": "",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "認同",
    "tsuLoo": "建議標音改做bîng-thài-tsú"
  },
  {
    "num": 2,
    "huagi": "核子潛艇",
    "taigiHan": "核子潛艇",
    "taigiLo": "Hi̍k-tsú-tsiâm-thíng",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "核子藏水艦",
    "phioTsng": "應討論",
    "tsuTsng": "核子藏水艦(tshàng-tsuí-kàm)",
    "phioLim": "認同",
    "tsuLim": "",
    "phioGiam": "認同",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "核子藏水艦hi̍k-tsú tshàng-tsuí-lām",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "認同",
    "tsuLoo": "建議標音改做「核子沬水艇hi̍k-tsú bī-tsuí-thíng」"
  },
  {
    "num": 3,
    "huagi": "核酸檢測",
    "taigiHan": "核酸檢測",
    "taigiLo": "Hi̍k-suan-kiám-tshik",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "認同",
    "tsuLim": "",
    "phioGiam": "應討論",
    "tsuGiam": "檢驗",
    "phioThiann": "應討論",
    "tsuThiann": "hi̍k-sng kiám-tshik",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "認同",
    "tsuLoo": "建議標音改做「hi̍k-sng kiám-tshik」"
  },
  {
    "num": 4,
    "huagi": "莫德納",
    "taigiHan": "莫德納",
    "taigiLo": "Bo̍h-tik-la̍p",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "建議(寫)莫德納 (唸)Moo-té-nah",
    "phioGiam": "認同",
    "tsuGiam": "Bo̍k-tik-la̍p",
    "phioThiann": "認同",
    "tsuThiann": "",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "應討論",
    "tsuKueh": "Bo̍k -tik-la̍p",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "應討論",
    "tsuSoo": "莫德那[Bo̍k-tik-ná]",
    "phioLoo": "認同",
    "tsuLoo": ""
  },
  {
    "num": 5,
    "huagi": "愛國者三型增程型飛彈",
    "taigiHan": "愛國者三型增程型飛彈",
    "taigiLo": "ài-kok-tsiá sann-hîng tsing-thîng-hîng hui-tuânn",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "三型 sam型?",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "Ài-kok-tsiá Sann-hîng Tsing-thîng-hîng Hui-tuânn(敢規个算一个專有名詞？抑是中央的「三型增程型」是補充、修飾成份？",
    "phioGiam": "認同",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "Ài-kok-tsiá Sann-hîng Tsing-thîng-hîng Hui-tuânn",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "認同",
    "tsuLoo": ""
  },
  {
    "num": 6,
    "huagi": "肚臍橙",
    "taigiHan": "肚臍丁",
    "taigiLo": "tōo-tsâi-ting",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "反對",
    "tsuLim": "肚臍橙tîng（柳丁對柳橙來）",
    "phioGiam": "認同",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "肚臍橙tōo-tsâi-tîng / tshiâng（案：咱講的「柳丁」照講是「柳橙」讀縒音去的，「丁」本底無「橙」的意思）",
    "phioHo": "應討論",
    "tsuHo": "因為肚臍臍橙肉質佇leh柑仔和柳丁之間, 所以民間有講\"柑\"有講\"丁\". 總是講丁的khah捷聽著的是\"臍丁\", 無\"肚\"字, 有\"財\"有\"丁\", 逐家真愛提來拜拜.",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "應討論",
    "tsuLoo": "建議改做「肚臍柑tōo-tsâi-kam」"
  },
  {
    "num": 7,
    "huagi": "帕金森氏症",
    "taigiHan": "帕金森病",
    "taigiLo": "Pheh-kim-sim-pēnn,Pheh-kim-sim-pīnn",
    "guagi": "Parkinson's diease",
    "tsukai": "帕: Pheh",
    "phioKhoo": "反對",
    "tsuKhoo": "Phá-kin-sòng 病",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "認同",
    "tsuLim": "Phà-kim-sim-pēnn",
    "phioGiam": "認同",
    "tsuGiam": "帕音phè",
    "phioThiann": "應討論",
    "tsuThiann": "帕金森症Phè-kim-sim-tsìng（案：「症」字台語有咧用）",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "應討論",
    "tsuSoo": "pha̍h-khín-sóng",
    "phioLoo": "認同",
    "tsuLoo": "建議標音改做Phè-kim-sim-pēnn/pīnn"
  },
  {
    "num": 8,
    "huagi": "黃龍",
    "taigiHan": "黃龍",
    "taigiLo": "n̂g-lîng",
    "guagi": "",
    "tsukai": "柑橘黃龍病",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "認同",
    "tsuLim": "n̂g-lîng or n̂g-liông？",
    "phioGiam": "認同",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "「龍」字有文白音（也成做方言差囉）",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "應討論",
    "tsuKueh": "n̂g-liông/lîng",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "應討論",
    "tsuSoo": "n̂g-liông-pēnn",
    "phioLoo": "應討論",
    "tsuLoo": "若是地名開頭字母愛大寫"
  },
  {
    "num": 9,
    "huagi": "熱帶性低氣壓",
    "taigiHan": "熱帶性低氣壓",
    "taigiLo": "Jia̍t-tài-sìng-te-khì-ap",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "認同",
    "tsuLim": "Jia̍t-tài-sìng Kē-khì-ap",
    "phioGiam": "認同",
    "tsuGiam": "kē khì-ap",
    "phioThiann": "應討論",
    "tsuThiann": "jia̍t-tài-sìng kē-khì-ap",
    "phioHo": "應討論",
    "tsuHo": "",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "應討論",
    "tsuLoo": "標音建議改做「jia̍t-tài-sìng kē-khì-ap」"
  },
  {
    "num": 10,
    "huagi": "核三位一體",
    "taigiHan": "核三位一體",
    "taigiLo": "hi̍k-sann-uī-tsi̍t-thé",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "認同",
    "tsuLim": "it-thé",
    "phioGiam": "應討論",
    "tsuGiam": "sam-uī it-thé",
    "phioThiann": "應討論",
    "tsuThiann": "hi̍k sann-uī it-thé",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "應討論",
    "tsuKueh": "hi̍k-sam-uī-it-thé",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "應討論",
    "tsuLoo": "建議標音改做「hi̍k sann-uī it-thé」"
  },
  {
    "num": 11,
    "huagi": "脊椎側彎",
    "taigiHan": "龍骨彎曲",
    "taigiLo": "liông-kut uan-khiau",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "贊同 「龍骨歪斜 liông-kut uai-tshua̍h」",
    "phioGiam": "認同",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "龍骨歪斜 （案：華語的『側彎』的『側』照講也著譯出來會較好勢，「歪斜」欲讀「uai-tshua̍h」抑是「uai-tshiâ」攏好」）",
    "phioHo": "應討論",
    "tsuHo": "側彎",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "應討論",
    "tsuLoo": "建議改做「龍骨歪斜 liông-kut uai-tshua̍h」"
  },
  {
    "num": 12,
    "huagi": "掩埋",
    "taigiHan": "掩埋",
    "taigiLo": "iám-mâi",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "反對",
    "tsuLim": "「埋tâi」一字就好",
    "phioGiam": "反對",
    "tsuGiam": "埋（tâi）",
    "phioThiann": "應討論",
    "tsuThiann": "埋tâi",
    "phioHo": "應討論",
    "tsuHo": ".若是kan-na掩埋, 建議直接用\"埋\"就好; 若是koh khah複雜的構詞,垃圾掩埋場\", 才來用\"掩埋\"",
    "phioKueh": "應討論",
    "tsuKueh": "iám-bâi",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "iam-bâi",
    "phioLoo": "認同",
    "tsuLoo": "用「埋tâi」就好"
  },
  {
    "num": 13,
    "huagi": "棲息地",
    "taigiHan": "生湠地",
    "taigiLo": "sinn-thuànn-tè",
    "guagi": "",
    "tsukai": "棲息地 tshe-sik-tē?（12/28SOT過音員照字念）",
    "phioKhoo": "應討論",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "habitat，慣勢蹛的自然環境。想無較好的翻譯，會當接受「生湠地」。",
    "phioGiam": "反對",
    "tsuGiam": "sing-ua̍h ê sóo-tsai",
    "phioThiann": "認同",
    "tsuThiann": "",
    "phioHo": "應討論",
    "tsuHo": "有聽過人用\"棲地(tshe-tē)",
    "phioKueh": "認同",
    "tsuKueh": "senn/sinn -thuànn-tè",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "生活地",
    "phioLoo": "認同",
    "tsuLoo": "建議補又音「senn-thuànn-tē」"
  },
  {
    "num": 14,
    "huagi": "蒸汽火車頭",
    "taigiHan": "水煙火車母",
    "taigiLo": "tsuí-ian hué-tshia-bó,tsuí-ian hé-tshia-bú",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "反對",
    "tsuKhoo": "蒸汽火車母",
    "phioTsng": "應討論",
    "tsuTsng": "",
    "phioLim": "認同",
    "tsuLim": "",
    "phioGiam": "認同",
    "tsuGiam": "",
    "phioThiann": "認同",
    "tsuThiann": "",
    "phioHo": "應討論",
    "tsuHo": "蒸汽火車也會當講是\"水煙車\", 所以建議共\"火\"字提掉, 變成\"火煙車母\", 按呢較減省",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "",
    "phioLoo": "認同",
    "tsuLoo": "標音建議改做「tsuí-ian hué-tshia-bó/hé-tshia-bú」"
  },
  {
    "num": 15,
    "huagi": "法式長棍麵包",
    "taigiHan": "法式長棍麭",
    "taigiLo": "huat-sik tn̂g-kùn-pháng",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "法國長麭",
    "phioTsng": "應討論",
    "tsuTsng": "法國長麭",
    "phioLim": "應討論",
    "tsuLim": "贊同「法式棍仔麭Huat-sik kùn-á-pháng」",
    "phioGiam": "認同",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "法國棍仔麭",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "應討論",
    "tsuSoo": "法國pháng",
    "phioLoo": "認同",
    "tsuLoo": "建議標音改做Huat-sik tn̂g-kùn-pháng"
  },
  {
    "num": 16,
    "huagi": "活摘器官",
    "taigiHan": "活摘器官",
    "taigiLo": "ua̍h-tiah khì-kuan",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "活取器官",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "活取器官",
    "phioGiam": "應討論",
    "tsuGiam": "動詞建議用「割」",
    "phioThiann": "應討論",
    "tsuThiann": "活取器官（案：台語的「摘」tiah是較倚「挽」抑是「選，指定」（文摘，摘名摘姓）的意思）",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "應討論",
    "tsuLoo": "建議改做「活取器官ua̍h tshú khì-kuan」"
  },
  {
    "num": 17,
    "huagi": "挹注",
    "taigiHan": "挹注",
    "taigiLo": "ip-tsù",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "反對",
    "tsuLim": "這款動詞應該看頂下文講予順，無適合直接詞對詞，避免未來予人誤用。",
    "phioGiam": "應討論",
    "tsuGiam": "灌入（臺日典）",
    "phioThiann": "應討論",
    "tsuThiann": "相添",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "應討論",
    "tsuKueh": "掠長補短 lia̍h-tn̂g-póo-té",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "補充/相添",
    "phioLoo": "應討論",
    "tsuLoo": "建議改做「補入póo-ji̍p」較好理解"
  },
  {
    "num": 18,
    "huagi": "搜尋",
    "taigiHan": "搜尋",
    "taigiLo": "soo-sîm",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "反對",
    "tsuLim": "搜揣tshiau-tshuē",
    "phioGiam": "應討論",
    "tsuGiam": "查",
    "phioThiann": "應討論",
    "tsuThiann": "搜揣",
    "phioHo": "應討論",
    "tsuHo": "一般台語講是\"搜揣\"?",
    "phioKueh": "認同",
    "tsuKueh": "",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "應討論",
    "tsuLoo": "考慮用「搜揣tshiau-tshuē/tshē」"
  },
  {
    "num": 19,
    "huagi": "脈衝光",
    "taigiHan": "mai衝光",
    "taigiLo": "mai-tshiong-kng",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "me̍h-tshiong-kng (Intense pulsed light )",
    "phioGiam": "應討論",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "「脈」字有文白音，新詞個人較會用文音",
    "phioHo": "應討論",
    "tsuHo": "me̍h-tshiong-kng？",
    "phioKueh": "應討論",
    "tsuKueh": "脈衝光（bi̍k-tshiong-kong/kng）",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "應討論",
    "tsuSoo": "[me̍h-tshiong-kng]",
    "phioLoo": "應討論",
    "tsuLoo": "建議照字標音做「me̍h-tshiong-kng」"
  },
  {
    "num": 20,
    "huagi": "晚更新世",
    "taigiHan": "晏更新世",
    "taigiLo": "uànn-king-sin-sè",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "華語的正式名稱是「更新世/晚更新期」，台語翻做「更新世/晏更新期」",
    "phioGiam": "應討論",
    "tsuGiam": "後更新世",
    "phioThiann": "應討論",
    "tsuThiann": "照字讀「晚Buán」",
    "phioHo": "應討論",
    "tsuHo": "",
    "phioKueh": "應討論",
    "tsuKueh": "晚更新世（Buán--king-sin-sè）",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "晚更新世[buán-……]",
    "phioLoo": "認同",
    "tsuLoo": ""
  },
  {
    "num": 21,
    "huagi": "蒸氣火車頭",
    "taigiHan": "蒸氣火車頭",
    "taigiLo": "tsing-khì hué-tshia-thâu, tsing-khì hé-tshia-thâu",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "蒸汽火車母",
    "phioTsng": "應討論",
    "tsuTsng": "蒸氣火車母(tsing-khì hué-tshia-bú)",
    "phioLim": "反對",
    "tsuLim": "用頂面條的水煙，莫用蒸汽",
    "phioGiam": "反對",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "建議用一體就好，個人選頂面彼條。（案：「火車頭」台語有家己的意思）",
    "phioHo": "應討論",
    "tsuHo": "車頭",
    "phioKueh": "應討論",
    "tsuKueh": "",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "認同",
    "tsuLoo": "標音建議改做「tsing-khì hué-tshia-thâu/hé-tshia-thâu」"
  },
  {
    "num": 22,
    "huagi": "大隊接力",
    "taigiHan": "紲力走標",
    "taigiLo": "suà-la̍t-tsáu-pio",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "住宅區 tsū-the̍h-khu",
    "phioTsng": "認同",
    "tsuTsng": "",
    "phioLim": "反對",
    "tsuLim": "厝宅區(tshù-the̍h-khu)",
    "phioGiam": "認同",
    "tsuGiam": "嘛會使講 tsū-the̍h-khu",
    "phioThiann": "應討論",
    "tsuThiann": "住宅區",
    "phioHo": "應討論",
    "tsuHo": "住宅",
    "phioKueh": "應討論",
    "tsuKueh": "住宅區（tsū-the̍h-khu）",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "應討論",
    "tsuSoo": "住宅區 沿用",
    "phioLoo": "應討論",
    "tsuLoo": "建議照字講做「住宅區tsū-the̍h-ku」"
  },
  {
    "num": 23,
    "huagi": "住宅區",
    "taigiHan": "徛家區",
    "taigiLo": "khiā-ke-khu",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "偶蹄目",
    "phioTsng": "應討論",
    "tsuTsng": "偶蹄目",
    "phioLim": "反對",
    "tsuLim": "雙蹄目siāng-tê-bo̍k(雙數奇數。「目」是專有名詞毋通改",
    "phioGiam": "應討論",
    "tsuGiam": "目＝類？",
    "phioThiann": "應討論",
    "tsuThiann": "雙蹄目",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "應討論",
    "tsuKueh": "ngóo-tê-bo̍k",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "應討論",
    "tsuLoo": "建議改做「雙蹄類 siang-tê-luī」"
  },
  {
    "num": 24,
    "huagi": "偶蹄目",
    "taigiHan": "偶蹄類",
    "taigiLo": "ngóo-tê-luī",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "應討論",
    "tsuTsng": "建議直接用滅火器（bia̍t-hué-khì）",
    "phioLim": "認同",
    "tsuLim": "接受「滅火器」",
    "phioGiam": "應討論",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "照字讀",
    "phioHo": "應討論",
    "tsuHo": "",
    "phioKueh": "應討論",
    "tsuKueh": "滅火器（bia̍t-hué-khì）",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "滅火器 沿用",
    "phioLoo": "應討論",
    "tsuLoo": "照字講做「bia̍t-hué/hé-khì」嘛真普遍"
  },
  {
    "num": 25,
    "huagi": "滅火器",
    "taigiHan": "拍火罐",
    "taigiLo": "phah-hué-kuàn",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "大隊接力",
    "phioTsng": "應討論",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "大隊走標",
    "phioGiam": "應討論",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "通討論",
    "phioHo": "認同",
    "tsuHo": "",
    "phioKueh": "應討論",
    "tsuKueh": "接棒走標tsiap-pāng-tsáu-pio",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "大隊接力 台語文音",
    "phioLoo": "應討論",
    "tsuLoo": "直接講做「大隊接力tuā-tuī tsiap-li̍k」"
  },
  {
    "num": 26,
    "huagi": "地面攔截網",
    "taigiHan": "地面攔截網",
    "taigiLo": "tē-bīn-nuâ-tsia̍t-bāng",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "地面接閘網",
    "phioTsng": "應討論",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "地面閘網tē-bīn-tsa̍h-bāng",
    "phioGiam": "反對",
    "tsuGiam": "地面攔閘/nuâ-tsa̍h/網（臺日有「攔閘」）",
    "phioThiann": "應討論",
    "tsuThiann": "地面攔閘網",
    "phioHo": "應討論",
    "tsuHo": "同\"攔截\"詞條, 會當考慮敢有欲用\"攔閘\"",
    "phioKueh": "應討論",
    "tsuKueh": "地面遮閘網（tē-bīn-jia/lia-tsa̍h-bāng）",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "地面攔閘網[tē-bīn-lân-tsa̍h-bāng]",
    "phioLoo": "應討論",
    "tsuLoo": "建議改做「地面攔閘網tē-bīn nuâ-tsa̍h-bāng」"
  },
  {
    "num": 27,
    "huagi": "矽砂",
    "taigiHan": "硅素",
    "taigiLo": "kuí-sòo",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "",
    "phioTsng": "應討論",
    "tsuTsng": "",
    "phioLim": "應討論",
    "tsuLim": "二氧化矽成分懸的石英砂叫做「矽砂」，「硅」是「矽」的舊譯，「硅素」是二氧化矽(Silica, SiO2)本身。愛翻做「矽砂si̍k-sua」",
    "phioGiam": "應討論",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "矽砂",
    "phioHo": "應討論",
    "tsuHo": "X素",
    "phioKueh": "應討論",
    "tsuKueh": "矽砂（si̍k-sua）",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "矽利康砂[silicon-sua]",
    "phioLoo": "應討論",
    "tsuLoo": "「硅」是中國用語，建議直接講做「矽砂si̍k-sua」"
  },
  {
    "num": 28,
    "huagi": "雨刷",
    "taigiHan": "雨鑢仔",
    "taigiLo": "hōo-lù-á",
    "guagi": "",
    "tsukai": "教典有收 雨撇仔、雨捽仔、雨抿仔",
    "phioKhoo": "應討論",
    "tsuKhoo": "雨掰 hōo-pé",
    "phioTsng": "應討論",
    "tsuTsng": "雨掰仔 (hōo-pé-á）",
    "phioLim": "反對",
    "tsuLim": "雨抿仔。毋若是掰雨水，確實有清潔的功能，佮齒抿仝款",
    "phioGiam": "認同",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "雨撇仔/ 雨捽仔 / uài-bah（案：日語借詞，wiper來的）",
    "phioHo": "應討論",
    "tsuHo": "雨捽仔感覺khah捷聽著?",
    "phioKueh": "應討論",
    "tsuKueh": "雨捽仔（hōo-sut-á）",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "應討論",
    "tsuSoo": "雨sut仔",
    "phioLoo": "應討論",
    "tsuLoo": "建議講做「雨抿仔hōo-bín-á」"
  },
  {
    "num": 29,
    "huagi": "接種",
    "taigiHan": "接種",
    "taigiLo": "tsiap-tsíng",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "認同",
    "tsuKhoo": "",
    "phioTsng": "反對",
    "tsuTsng": "注疫苗",
    "phioLim": "反對",
    "tsuLim": "若是指疫苗，用注疫苗就好",
    "phioGiam": "反對",
    "tsuGiam": "注（tsù）",
    "phioThiann": "應討論",
    "tsuThiann": "『接種』台語論真會當講「種」，可比「種珠；種痘」，當然若是感覺這是「詞彙化」矣，按呢講「注」也是好勢",
    "phioHo": "應討論",
    "tsuHo": "若是kan-na接種, 建議直接用\"注\"就好; 若是koh khah複雜的構詞, 像\"(疫苗)接種卡\", 才來用\"接種\".",
    "phioKueh": "應討論",
    "tsuKueh": "注（tsù）",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "注(預防)射",
    "phioLoo": "應討論",
    "tsuLoo": "標音建議改做「tsiap-tsìng」"
  },
  {
    "num": 30,
    "huagi": "彈劾",
    "taigiHan": "彈劾",
    "taigiLo": "tuânn-hik",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "反對",
    "tsuKhoo": "",
    "phioTsng": "反對",
    "tsuTsng": "",
    "phioLim": "反對",
    "tsuLim": "頂面條已經有tân-hik",
    "phioGiam": "反對",
    "tsuGiam": "",
    "phioThiann": "應討論",
    "tsuThiann": "建議用一體就好，個人選頂面彼條。（案：「責備」意思的「彈」台語讀「tân」）",
    "phioHo": "應討論",
    "tsuHo": "彈",
    "phioKueh": "應討論",
    "tsuKueh": "",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "認同",
    "tsuSoo": "",
    "phioLoo": "反對",
    "tsuLoo": "收「tân-hik」就好"
  },
  {
    "num": 31,
    "huagi": "窯烤麵包",
    "taigiHan": "窯麵包",
    "taigiLo": "iô-mī-pau",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "窯烘麭",
    "phioTsng": "應討論",
    "tsuTsng": "窯烘麭(iô-hang-pháng)",
    "phioLim": "反對",
    "tsuLim": "窯麭iô-pháng",
    "phioGiam": "應討論",
    "tsuGiam": "iô-hang-pháng",
    "phioThiann": "應討論",
    "tsuThiann": "窯烘麭",
    "phioHo": "應討論",
    "tsuHo": "窯麭？",
    "phioKueh": "應討論",
    "tsuKueh": "iô-hang-mī-pau（與30同「麭」？）",
    "phioTshi": "認同",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "窯烘pháng",
    "phioLoo": "應討論",
    "tsuLoo": "建議改做「窯烘麵包／麭 iô hang mī-pau/pháng」"
  },
  {
    "num": 32,
    "huagi": "緩衝時間",
    "taigiHan": "huān衝的時間",
    "taigiLo": "huān-tshiong ê sî-kan",
    "guagi": "",
    "tsukai": "",
    "phioKhoo": "應討論",
    "tsuKhoo": "緩衝時間",
    "phioTsng": "應討論",
    "tsuTsng": "伸勼（tshun-kiu）時間",
    "phioLim": "反對",
    "tsuLim": "支持「伸勼時間tshun-kiu sî-kan」",
    "phioGiam": "應討論",
    "tsuGiam": "寬限時間 khuan-ān sî-kan",
    "phioThiann": "應討論",
    "tsuThiann": "伸勼時間",
    "phioHo": "應討論",
    "tsuHo": "A-sóo-bih的時間",
    "phioKueh": "應討論",
    "tsuKueh": "伸勼時間（tshun-kiu sî-kan）",
    "phioTshi": "應討論",
    "tsuTshi": "",
    "phioSoo": "反對",
    "tsuSoo": "tshun-kiu的時間",
    "phioLoo": "應討論",
    "tsuLoo": "建議照字唸做「緩衝時間 uān-tshiong sî-kan」"
  }
 ]
