let uhuanikData = [
  {
    num: 1,
    huagi: "大亨",
    taigiHan: "好額人",
    taigiLo: "hó-gia̍h-lâng",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "大好額人",
    phioTsng: "應討論",
    tsuTsng: "大好額人",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "無一定干焦好額",
    phioThiann: "應討論",
    tsuThiann:
      "大色人 tuā-sik-lâng（案：『大亨』，照講毋但「好額」爾，著愛有錢閣有勢）",
    phioHo: "應討論",
    tsuHo:
      '”大亨"毋若好額, 一般koh是某一个產業的成功經營者, 所以會當考慮共大亨翻作"(某一个產業的)頭人"',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "探討「大亨」的詞源，是對英語 tycoon 音譯來的，英語閣是對日語「大君」音譯來的。佇日語原本是幕府時代的將軍，英語主要用來表示大企業家，所以多數人會感覺「大亨」是大好額人，其實有權勢嘛是要緊的意涵，佮我講的「大粒攄」意思有合。",
  },
  {
    num: 2,
    huagi: "宅經濟",
    taigiHan: "宅經濟",
    taigiLo: "the̍h-king-tsè",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "踮跤經濟",
    phioGiam: "認同",
    tsuGiam: "踮厝經濟",
    phioThiann: "應討論",
    tsuThiann:
      "居家經濟 ki-ka king-tsè / ku-ka king-tsè（案：「居家」《臺日》有收）",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「跔厝經濟 ku-tshù king-tsè」",
  },
  {
    num: 3,
    huagi: "珍珠奶茶",
    taigiHan: "粉圓牛奶茶",
    taigiLo: "hún-înn gû-ling tê",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "真珠奶茶已經普遍",
    phioGiam: "應討論",
    tsuGiam: "真珠奶茶",
    phioThiann: "應討論",
    tsuThiann: "真珠奶茶 tsin-tsu ling-tê",
    phioHo: "應討論",
    tsuHo: "真珠奶茶",
    phioKueh: "認同",
    tsuKueh: "建議照字面真珠奶茶（tsin-tsu ling-tê），所講的內容是「粉圓」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「真珠奶茶 tsin-tsu ling/lin/ni-tê」",
  },
  {
    num: 4,
    huagi: "布丁",
    taigiHan: "布丁,熟卵乳",
    taigiLo: "pòo-ting,si̍k-nn̄g-ling",
    guagi: "",
    tsukai:
      "熟卵乳的來源： https://www.youtube.com/watch?v=1RD9QRpPjTA&ab_channel=%E5%92%B1K%C3%B3ng%E5%8F%B0%E8%AA%9E",
    phioKhoo: "認同",
    tsuKhoo: "布丁",
    phioTsng: "認同",
    tsuTsng: "布丁",
    phioLim: "應討論",
    tsuLim: "卵凍、甜凍",
    phioGiam: "認同",
    tsuGiam: "布丁",
    phioThiann: "應討論",
    tsuThiann: "布丁 pòo-ting",
    phioHo: "應討論",
    tsuHo: "布丁",
    phioKueh: "應討論",
    tsuKueh: "照音譯pudding，抑是欲講「雞卵凍（ke-nn̄g-tàng）」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「布丁 pòo-ting」",
  },
  {
    num: 5,
    huagi: "鮪魚蛋餅",
    taigiHan: "串仔卵餅",
    taigiLo: "tshǹg-á nn̄g-piánn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "串仔魚卵餅 tshǹg-á-hî nn̄g-piánn / \ntshǹg-á-hû nn̄g-piánn",
    phioHo: "認同",
    tsuHo: "串仔魚卵餅",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「串仔魚卵餅 tshǹg-á-hî/hû nn̄g-piánn」",
  },
  {
    num: 6,
    huagi: "檸檬紅茶",
    taigiHan: "檸檬紅茶",
    taigiLo: "le-bóng âng-tê",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "檸檬紅茶 lê-bóng âng-tê",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "lê-bóng",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「檸檬紅茶 lê-bóng âng-tê」",
  },
  {
    num: 7,
    huagi: "大冰奶",
    taigiHan: "大冰奶",
    taigiLo: "tuā-ping-ling",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann:
      "大杯冰奶茶 tuā pue ping-ling-tê【案：主要是台語的具體名詞若欲佮形容詞敆，一般著愛有「量詞」。可比：大台車；細尾蛇。我了解『大冰奶』是簡稱，總是直透照字譯予人真躊躇。】",
    phioHo: "認同",
    tsuHo: "大杯冰奶茶",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 8,
    huagi: "三明治",
    taigiHan: "俗麭𩛩",
    taigiLo: "sio̍k-pháng-kauh",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "sio̍k-pháng-kauh / siok-pháng-kauh",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh:
      "雖講過去逐家慣勢用日語講法，毋過這馬少年的講「三明治」（sam-bîng-tì）嘛講甲誠普遍",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 9,
    huagi: "漢堡",
    taigiHan: "漢堡,和肉敆",
    taigiLo: "hàn-pó,hām-bah-kap",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "漢堡",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "建議譀肉敆為主，漢堡第二",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "美國割包 Bí-kok kuah-pau；和肉佮 hām-bah-kah",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh:
      "阮幾若年前新聞就講麭𩛩（pháng-kauh），毋知各位前輩敢會當接受這款講法",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議寫做「和肉佮 hām-bah-kah」、美國割包 bí-kok guah-pau」",
  },
  {
    num: 10,
    huagi: "薯條",
    taigiHan: "馬鈴薯條, 馬鈴薯簽",
    taigiLo: "má-lîng-tsî-tiâu, má-lîng-tsî-tshiam",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "馬鈴薯條",
    phioTsng: "認同",
    tsuTsng: "馬鈴薯條",
    phioLim: "應討論",
    tsuLim: "馬鈴薯條má-lîng-tsî-tiâu",
    phioGiam: "應討論",
    tsuGiam: "薯條嘛有番薯的",
    phioThiann: "認同",
    tsuThiann: "馬鈴薯糋 má-lîng-tsî-tsìnn / má-lîng-tsû-tsìnn",
    phioHo: "應討論",
    tsuHo: "馬鈴薯條",
    phioKueh: "認同",
    tsuKueh: "嘛有誠濟人講bé-lîng-tsî",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「馬鈴薯條 má-lîng-tsî/tsû-tiâu」",
  },
  {
    num: 11,
    huagi: "雞塊",
    taigiHan: "雞糋, 雞塊",
    taigiLo: "ke-tsìnn, ke-tè",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "雞塊仔ke-tè-á",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "雞肉糋 ke-bah-tsìnn / kue-bah-tsìnn",
    phioHo: "應討論",
    tsuHo: "美國雞肉糋?",
    phioKueh: "認同",
    tsuKueh: "雞糋",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「雞肉角 ke/kue-bah-kak」",
  },
  {
    num: 12,
    huagi: "吐司",
    taigiHan: "俗麭",
    taigiLo: "sio̍k-pháng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "sio̍k-pháng / siok-pháng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 13,
    huagi: "玉米濃湯",
    taigiHan: "番麥濁湯,番麥羹",
    taigiLo: "huan-be̍h lô-thng, huan-be̍h kinn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "番麥濁湯",
    phioLim: "應討論",
    tsuLim: "番麥羹",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "番麥羹 huan-be̍h-kenn / huan-be̍h-kenn-kinn",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "番麥牽羹",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「番麥羹湯 huan-be̍h-kenn/kinn-thng」",
  },
  {
    num: 14,
    huagi: "天然氣",
    taigiHan: "天然氣",
    taigiLo: "thian-jiân-khì ,thian-liân-khì",
    guagi: "natural gas",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "thian-jiân-khì / thian-liân-khì",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "民間嘛有講「天然瓦斯」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "補「然」又音「liân」",
  },
  {
    num: 15,
    huagi: "液化",
    taigiHan: "液化",
    taigiLo: "i̍k-huà",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "建議照專有名詞，解釋才講是地基含（kâm）水",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 16,
    huagi: "鼻竇炎",
    taigiHan: "鼻竇炎",
    taigiLo: "phīnn-tōo-iām",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "補「鼻」又音「phī」",
  },
  {
    num: 17,
    huagi: "人臉辨識",
    taigiHan: "人面辨識",
    taigiLo: "lâng-bīn piān-sik",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 18,
    huagi: "大使館",
    taigiHan: "大使館",
    taigiLo: "tāi-sài-kuán",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 19,
    huagi: "失智症",
    taigiHan: "失智症",
    taigiLo: "sit-tì-tsìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 20,
    huagi: "伊斯蘭",
    taigiHan: "伊斯蘭",
    taigiLo: "I-su-lân",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "I-su-lân",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "I-su-lân",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "I-su-lân",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "開頭字母愛大寫「I-su-lân」",
  },
  {
    num: 21,
    huagi: "移工、外籍勞工",
    taigiHan: "移工,外勞",
    taigiLo: "î-kang, guā-lô",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "移工、外籍勞工。簡稱另外",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "移工 î-kang",
    phioHo: "認同",
    tsuHo: "移工, 避免歧視",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo:
      "89已經有「移工」，「外勞」有歧視的感覺，建議用全名「外籍勞工 guā-tsi̍k lô-kang」,抑是收「移工」就好",
  },
  {
    num: 22,
    huagi: "移工",
    taigiHan: "移工",
    taigiLo: "î-kang",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 23,
    huagi: "冰風暴",
    taigiHan: "冰風暴",
    taigiLo: "ping-hong-pō　",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "敢是文音「ping-hong-po̍k」較順",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 24,
    huagi: "巡洋艦",
    taigiHan: "巡洋艦",
    taigiLo: "sûn-iûnn-lām",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 25,
    huagi: "空心磚",
    taigiHan: "空心磚",
    taigiLo: "khang-sim-tsng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 26,
    huagi: "電鋸",
    taigiHan: "電鋸",
    taigiLo: "tiān-kì,tiān-kù",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 27,
    huagi: "魁北克",
    taigiHan: "魁北克",
    taigiLo: "Khue-pak-khik",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 28,
    huagi: "豁免",
    taigiHan: "豁免",
    taigiLo: "hat-bián",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 29,
    huagi: "網路防火牆",
    taigiHan: "網路防火牆",
    taigiLo: "bāng-lōo hông-hué-tshiûnn, bāng-lōo hông-hé-tshiûnn",
    guagi: "",
    tsukai: "網路防火牆 firewall",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "bāng-lōo hông-hué-tshiûnn / bāng-lōo hông-hé-tshiûnn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「火」補又音「hé」",
  },
  {
    num: 30,
    huagi: "鼻胃管",
    taigiHan: "鼻胃管",
    taigiLo: "phīnn-uī-kóng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "補「鼻」又音「phī」",
  },
  {
    num: 31,
    huagi: "共伴效應",
    taigiHan: "共伴效應",
    taigiLo: "kiōng-phuān hāu-ìng",
    guagi: "",
    tsukai: "洪敏貞新聞台語節目介紹",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 32,
    huagi: "入賬",
    taigiHan: "入數",
    taigiLo: "ji̍p-siàu,li̍p-siàu",
    guagi: "",
    tsukai: "台文華文線頂辭典",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "ji̍p-siàu / li̍p-siàu",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "補「入」又音「li̍p」",
  },
  {
    num: 33,
    huagi: "虛擬貨幣,加密貨幣",
    taigiHan: "虛擬貨幣",
    taigiLo: "hi-gí huè-pè, ka-bi̍t huè-pè",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "分兩條",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "hi-gí huè-pè / hi-gí hè-pè\nka-bi̍t huè-pè / ka-bi̍t hè-pè",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「貨」有「hè」的又音",
  },
  {
    num: 34,
    huagi: "衝鋒槍",
    taigiHan: "衝鋒銃",
    taigiLo: "tshiong-hong-tshìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 35,
    huagi: "諾羅病毒",
    taigiHan: "諾羅病毒",
    taigiLo: "Lo̍k-lô pēnn-to̍k ,Lo̍k-lô pīnn-to̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "Lo̍k-lô pēnn-to̍k / Lo̍k-lô pīnn-to̍k",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "補「病」又音「pīnn」",
  },
  {
    num: 36,
    huagi: "內輪差",
    taigiHan: "內輪差",
    taigiLo: "lāi-lián-tsha",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 37,
    huagi: "鎮暴槍",
    taigiHan: "鎮暴銃",
    taigiLo: "tìn-pō-tshìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "tìn-pō",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "tìn-pō-tshìng",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "標音改做「tìn-pō-tshìng」",
  },
  {
    num: 38,
    huagi: "誤點",
    taigiHan: "慢分",
    taigiLo: "bān-hun",
    guagi: "rock music",
    tsukai: "台文華文線頂辭典",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「慢分」是在來就有的詞",
  },
  {
    num: 39,
    huagi: "搖滾樂",
    taigiHan: "搖滾樂",
    taigiLo: "iô-kún-ga̍k,iâu-kún-ga̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "iô-kún-ga̍k",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "iô 就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「iô-kún-ga̍k」",
  },
  {
    num: 40,
    huagi: "自閉症",
    taigiHan: "自閉症",
    taigiLo: "tsū-pì-tsìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 41,
    huagi: "熱氣球",
    taigiHan: "熱氣球",
    taigiLo: "jia̍t-khì-kiû, lia̍t-khì-kiû",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 42,
    huagi: "後遺症",
    taigiHan: "病尾, 後遺症",
    taigiLo: "pēnn-bué,pēnn-bé, āu-uî-tsìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "後遺症",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "病尾pēnn-bué / pīnn-bé；後遺症 hiō-uî-tsìng / hōo-uî-tsìng",
    phioHo: "認同",
    tsuHo: "病尾",
    phioKueh: "認同",
    tsuKueh: "建議用專有名詞後遺症（āu-uî-tsìng），解釋會用得講是病尾、留屎虎",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「尾」有又音「bé」",
  },
  {
    num: 43,
    huagi: "考古",
    taigiHan: "考古",
    taigiLo: "khó-kóo",
    guagi: "",
    tsukai: "台文華文線頂辭典",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 44,
    huagi: "奶油",
    taigiHan: "奶油,bá-tah",
    taigiLo: "ling-iû,bá-tah",
    guagi: "Phytoncide",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "bá-tah",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "bá-tah; khu-lì-mù",
    phioHo: "認同",
    tsuHo: "bá-tah",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 45,
    huagi: "芬多精",
    taigiHan: "芬多精",
    taigiLo: "hun-to-tsing",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 46,
    huagi: "淋巴",
    taigiHan: "淋巴",
    taigiLo: "lîm-pa",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 47,
    huagi: "便條紙,便利貼",
    taigiHan: "便利貼",
    taigiLo: "piān-lī-tah",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 48,
    huagi: "滑板",
    taigiHan: "趨枋",
    taigiLo: "tshu-pang",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 49,
    huagi: "品勢",
    taigiHan: "品勢",
    taigiLo: "phín-sè",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 50,
    huagi: "夜光粉",
    taigiHan: "夜光粉",
    taigiLo: "iā-kng-hún",
    guagi: "Tourette syndrome",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 51,
    huagi: "妥瑞症",
    taigiHan: "妥瑞症",
    taigiLo: "Thò-suī-tsìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "症羅馬字拍毋著",
    phioThiann: "認同",
    tsuThiann:
      "Thó-suī-tsìng【案：「妥」字有「上聲」的來源，《甘字典》也有收，這款現代詞敢欲就直透對應「陰上」的讀法？】",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "應該是「妥瑞氏症 Thò-suī-sī-tsìng」",
  },
  {
    num: 52,
    huagi: "電子郵件",
    taigiHan: "電子批",
    taigiLo: "tiān-tsú-phue,tiān-tsú-phe",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "贊成，總是也有人干焦講「電批 tiān-phue / tiān-phe」",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "補「批」又音「phe」",
  },
  {
    num: 53,
    huagi: "聊天室",
    taigiHan: "開講室",
    taigiLo: "khai-káng-sik",
    guagi: "",
    tsukai: "教典有收，應該免討論",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 54,
    huagi: "可蘭經",
    taigiHan: "可蘭經",
    taigiLo: "Khóo-lân-king",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "Khó-lân-king",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "照字音是「Khó-lân-king」。另外有「古蘭經Kóo-lân-king」的寫法。",
  },
  {
    num: 55,
    huagi: "營養午餐",
    taigiHan: "營養午餐",
    taigiLo: "îng-ióng ngóo-tshan",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "抑是「營養中晝頓」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 56,
    huagi: "搜索票",
    taigiHan: "搜索票",
    taigiLo: "soo-sik-phiò",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 57,
    huagi: "木棉花",
    taigiHan: "斑芝花",
    taigiLo: "pan-tsi-hue",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "班芝(花)",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "教育部辭典有收木棉bo̍k-mî",
    phioThiann: "認同",
    tsuThiann: "斑芝花 pan-tsi-hue；木棉花 bo̍k-mî-hue",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "建議生物盡量照科學分類講木棉花（bo̍k-mî-hue），臺日嘛有收",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 58,
    huagi: "蛋白質",
    taigiHan: "卵白質",
    taigiLo: "nn̄g-pe̍h-tsit",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "蛋白質",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 59,
    huagi: "狂犬病",
    taigiHan: "痟狗病",
    taigiLo: "siáu-káu-pēnn, siáu-káu-pīnn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "pēnn主音",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "siáu-káu-pēnn / siáu-káu-pīnn",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「病」通行腔「pēnn」，教典收「痟狗症siáu-káu-tsìng」",
  },
  {
    num: 60,
    huagi: "街友",
    taigiHan: "街友",
    taigiLo: "ke-iú, kue-iú",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "遊民 iû-bîn【案：《臺日》有收「遊民」】",
    phioHo: "認同",
    tsuHo:
      "街友是專工號的, 為著無beh歧視, 有專門的目的. 所以會當考慮照華語翻就好.",
    phioKueh: "認同",
    tsuKueh: "流浪漢敢若有歧視",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "補「街」又音「kue」",
  },
  {
    num: 61,
    huagi: "幹細胞",
    taigiHan: "幹細胞",
    taigiLo: "kàn-sè-pau, kàn-suè-pau",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "kàn-sè-pau / kàn-suè-pau",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "補「細」又音「suè」",
  },
  {
    num: 62,
    huagi: "多巴胺",
    taigiHan: "多巴胺",
    taigiLo: "to-pa-at",
    guagi: "",
    tsukai: "甘字典文讀音「胺 at」",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "to-pa-an",
    phioGiam: "認同",
    tsuGiam: "to-pa-an",
    phioThiann: "認同",
    tsuThiann: "to-pa-an",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "羅馬字愛改做「to-pa-an」",
  },
  {
    num: 63,
    huagi: "留言",
    taigiHan: "留話,留言",
    taigiLo: "lâu-uē,lâu-giân",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "留話 lâu-uē",
    phioHo: "認同",
    tsuHo: "留話",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「寄話 kià-uē」",
  },
  {
    num: 64,
    huagi: "首頁",
    taigiHan: "頭頁",
    taigiLo: "thâu-ia̍h",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 65,
    huagi: "貼文",
    taigiHan: "貼文,鋪文",
    taigiLo: "tah-bûn,phoo-bûn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "鋪文就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "建議鋪文優先",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「鋪文 phoo-bûn」",
  },
  {
    num: 66,
    huagi: "舍利子",
    taigiHan: "舍利子",
    taigiLo: "sià-lī-tsú",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo:
      "舍利子有2个意思，定用的是講修行的人過身了後燒出來的物；另外，佇「心經」內面也有「舍利子」(舍利弗)的名。總是若用sià-lī-tsú就2種攏無問題.",
    phioKueh: "應討論",
    tsuKueh: "sià-lī-tsú",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「舍利子」是「sià-lī-tsú」抑「sià-lī-tsí」",
  },
  {
    num: 67,
    huagi: "超大胞",
    taigiHan: "超大胞",
    taigiLo: "tshiau-tuā-pau",
    guagi: "Supercell",
    tsukai: "氣象詞彙",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "Supercell",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "超級雷暴 tshiau-kip luî-pō",
    phioHo: "應討論",
    tsuHo: '敢是"超級捲螺仔風"?',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 68,
    huagi: "人蛇集團",
    taigiHan: "人蛇集團",
    taigiLo: "jîn-siâ tsi̍p-thuân, lâng-tsuâ tsi̍p-thuân",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "jîn-siâ tsi̍p-thuân",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "lâng-tsuâ就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "lâng-tsuâ tsi̍p-thuân",
    phioHo: "認同",
    tsuHo: "lâng-tsuâ",
    phioKueh: "應討論",
    tsuKueh: "人口販仔集團（jîn-kháu huàn-á tsi̍p-thuân）",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議標音做「lâng-tsuâ tsi̍p-thuân」",
  },
  {
    num: 69,
    huagi: "考古題",
    taigiHan: "考古題,公媽題",
    taigiLo: "khó-kóo-tê, kong-má-tê",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "考古題",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "論真華語的考古題嘛是笑詼講法，有佇無仝所在看著人講「公媽題」，嘛算是台語家己生出來的詞，會使考慮。",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "khó-kóo-tê / khó-kóo-tuê",
    phioHo: "認同",
    tsuHo: "考古題，予和考古一致",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「考古題 khó-kóo-tê/tuê」就好",
  },
  {
    num: 70,
    huagi: "蝦皮",
    taigiHan: "蝦皮",
    taigiLo: "Hê-phuê, Hê-phê",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "敢是shopee?",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: "私人公司的名建議尊重原公司, 無一定愛列入咱的詞條內面",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo:
      "「蝦皮」臺語是「蝦卑 hê-pi」，若是「蝦皮購物」的「蝦皮」建議用羅馬字寫做「Siá-phih」",
  },
  {
    num: 71,
    huagi: "蒲燒",
    taigiHan: "蒲燒",
    taigiLo: "pôo-sio",
    guagi: "",
    tsukai: "相關詞彙：蒲燒鰻魚、蒲燒鯛魚、蒲燒醬",
    phioKhoo: "應討論",
    tsuKhoo: '濃湯 "膏湯"',
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "烘",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 72,
    huagi: "豎琴",
    taigiHan: "徛琴",
    taigiLo: "khiā-khîm",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: '記得有聽過樂團的人講過"ha-phuh", 會當考慮敢有beh用外來語',
    phioKueh: "應討論",
    tsuKueh: "sū-khîm",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 73,
    huagi: "伺服器",
    taigiHan: "伺服器,服務器",
    taigiLo: "su-ho̍k-khì,ho̍k-bū-khì",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "伺服器sū-ho̍k-khì",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "伺服器 sū-ho̍k-khì",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「伺服器 sū-ho̍k-khì」",
  },
  {
    num: 74,
    huagi: "發泡錠",
    taigiHan: "發泡片,起泡片",
    taigiLo: "puh-pho-phìnn, khí-pho-phìnn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "起泡片",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "起波片 khí-pho-phìnn",
    phioHo: "認同",
    tsuHo: "起泡片",
    phioKueh: "認同",
    tsuKueh: "發泡片",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「起波片 khí-pho-phìnn」",
  },
  {
    num: 75,
    huagi: "扭蛋,轉蛋",
    taigiHan: "捘卵,𨑨迌卵,轉卵",
    taigiLo: "tsūn-nn̄g,tshit-thô-nn̄g,tsuán-nn̄g",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "捘卵",
    phioGiam: "認同",
    tsuGiam: "捘卵",
    phioThiann: "認同",
    tsuThiann: "捘卵 tsūn-nn̄g",
    phioHo: "認同",
    tsuHo: "捘卵",
    phioKueh: "認同",
    tsuKueh: "捘卵敢若講誠久",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「捘卵 tsūn-nn̄g」",
  },
  {
    num: 76,
    huagi: "椰果",
    taigiHan: "椰子肉,椰果",
    taigiLo: "iâ-tsí-bah,iâ-kó",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "椰果就好",
    phioGiam: "認同",
    tsuGiam: "椰果（是椰水製造的毋是椰肉）",
    phioThiann: "認同",
    tsuThiann: "椰果 iâ-kó",
    phioHo: "認同",
    tsuHo: "椰果",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「椰子肉 iâ-tsí-bah」",
  },
  {
    num: 77,
    huagi: "薯餅",
    taigiHan: "馬鈴薯餅",
    taigiLo: "má-lîng-tsî-piánn",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "馬鈴薯糋餅 má-lîng-tsî tsìnn-piánn / má-lîng-tsû tsìnn-piánn",
    phioHo: "應討論",
    tsuHo: "馬鈴薯餅",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「馬鈴薯餅 má-lîng-tsî/tsû-piánn」",
  },
  {
    num: 78,
    huagi: "復活節",
    taigiHan: "閣活節,復活節",
    taigiLo: "koh-ua̍h-tseh,ho̍k-ua̍h-tseh",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "ho̍k-ua̍h-tseh",
    phioTsng: "認同",
    tsuTsng: "復活節",
    phioLim: "應討論",
    tsuLim: "教會若像攏講閣活節Koh-ua̍h-tseh",
    phioGiam: "認同",
    tsuGiam: "捌聽教會的人講閣活",
    phioThiann: "認同",
    tsuThiann: "閣活節 koh-ua̍h-tseh / koh-ua̍h-tsueh【案：教會內底是按呢講】",
    phioHo: "認同",
    tsuHo: "閣活節(既然是宗教的節日，不如就尊重教會用法)",
    phioKueh: "應討論",
    tsuKueh: "臺日是收「Koh-ua̍h-tseh（閣活節）」，個人認為Ho̍k-ua̍h-tseh較順",
    phioTshi: "認同",
    tsuTshi: "復活節",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "開頭字母愛大寫「Koh-ua̍h-tseh/tsueh, Ho̍k-ua̍h-tseh/tsueh」",
  },
  {
    num: 79,
    huagi: "狒狒",
    taigiHan: "人熊,狒狒",
    taigiLo: "lâng-hîm,huì-huì",
    guagi: "baboon",
    tsukai: "台日典",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "人熊較好講，狒狒是專科詞，建議兩个攏收",
    phioGiam: "認同",
    tsuGiam: "人熊",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh:
      "臺日有收「狒」（huì），是生物的專有名詞，是猴科、狒狒屬；熊是熊科、熊亞科、熊屬。建議直接如虎豹獅象，講「狒」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「人熊 lâng-hîm」",
  },
  {
    num: 80,
    huagi: "狙擊",
    taigiHan: "狙擊",
    taigiLo: "tsu-kik",
    guagi: "",
    tsukai: "相關詞彙：狙擊手、狙擊槍",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "咱有講「暗殺」，若感覺無一定是「殺」，會當取「擊」，「暗擊」",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "暗殺 àm-sat",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo:
      "狙擊「暗中考銃àm-tiong khó-tshìng」、狙擊手「暗殺手àm-sat-tshiú」\n",
  },
  {
    num: 81,
    huagi: "浮屍",
    taigiHan: "浮屍",
    taigiLo: "phû-si",
    guagi: "",
    tsukai: "台文華文線頂辭典",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "應該是水流屍？",
    phioGiam: "認同",
    tsuGiam: "水流屍",
    phioThiann: "應討論",
    tsuThiann: "水流屍 tsuí-lâu-si",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "抑是「水流屍」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「水流屍tsuí-lâu-si」（臺日）",
  },
  {
    num: 82,
    huagi: "狂鹿症",
    taigiHan: "狂鹿症,痟鹿症",
    taigiLo: "kông-lo̍k-tsìng, siáu-lo̍k-tsìng",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "痟鹿症",
    phioLim: "應討論",
    tsuLim: "佮痟狗病對應，會使用痟鹿症",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "痟鹿仔症 siáu-lo̍k-á-tsìng",
    phioHo: "應討論",
    tsuHo:
      '狂鹿症khah親像"狂牛病", 和狂犬病應該是khah無仝. 會當思考和"狂牛症"做伙處理.',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「痟鹿症」",
  },
  {
    num: 83,
    huagi: "小抹香鯨",
    taigiHan: "吐血鯃",
    taigiLo: "thòo-huih-ngôo",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "小抹香鯨科、屬。建議用小抹香鯨sió-buah-hiong-king",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "吐血鯃 thòo-hueh-ngôo / thòo-huih-ngôo",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "建議照生物分類直接講「小抹香鯨」",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "「血」通行腔「hueh」",
  },
  {
    num: 84,
    huagi: "迷客夏",
    taigiHan: "迷客夏",
    taigiLo: "Bê-khik-hā",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "Bê-kheh-hā?",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: "私人公司的名建議尊重原公司, 無一定愛列入咱的詞條內面",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "這是商標，是「Milksha」的音譯，建議照英語音譯做「Mi-lú-kú-siah」",
  },
  {
    num: 85,
    huagi: "焊接",
    taigiHan: "拋電龜",
    taigiLo: "pha-tiān-ku",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "",
    tsuLim: "khóo-teh",
    phioGiam: "認同",
    tsuGiam: "銲huānn",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: "焊接",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「燒黏 sio-liâm」",
  },
  {
    num: 86,
    huagi: "麥克風",
    taigiHan: "麥克風",
    taigiLo: "mái-khù",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "mài-kuh？",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "mài-khù / mài-khuh / mài-kù / mài-kuh",
    phioHo: "認同",
    tsuHo: "2个音攏收",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "直接用羅馬字「mài-kù」",
  },
  {
    num: 87,
    huagi: "手搖杯,手搖飲",
    taigiHan: "手摵茶,手搖杯",
    taigiLo: "tshiú-tshik-tê,tshiú-iâu-pue",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "手搖: 手摵",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "摵仔杯、摵仔飲",
    phioGiam: "認同",
    tsuGiam: "用「摵」",
    phioThiann: "認同",
    tsuThiann: "手摵茶 tshiú-tshi̍k-tê",
    phioHo: "認同",
    tsuHo: "手摵茶",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「手摵茶／杯／飲料店 tshiú-tshi̍k-tê/pue/ím-liāu-tiàm」",
  },
  {
    num: 88,
    huagi: "吃到飽",
    taigiHan: "食甲飽,做你食",
    taigiLo: "tsia̍h-kah-pá,tsò-lí-tsia̍h",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "食甲飽就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "食甲飽 tsia̍h-kah-pá",
    phioHo: "認同",
    tsuHo: "食甲飽",
    phioKueh: "認同",
    tsuKueh: "食到（kàu）飽慢慢仔嘛聽有，抑是食迵海、見在你食",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「在你食 tsāi-lí-tsia̍h」",
  },
  {
    num: 89,
    huagi: "普洱茶",
    taigiHan: "臭殕茶,普洱茶",
    taigiLo: "tàu-phú-lê,phóo-ní-tê",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "臭殕茶",
    phioTsng: "認同",
    tsuTsng: "普洱茶",
    phioLim: "應討論",
    tsuLim: "建議收普洱茶就好",
    phioGiam: "認同",
    tsuGiam: "普洱茶",
    phioThiann: "認同",
    tsuThiann: "臭殕茶 tshàu-phú-tê；普洱茶 phóo-jī-tê / phóo-jínn-tê",
    phioHo: "應討論",
    tsuHo: "普洱/普洱茶",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「臭殕茶」標音愛改做「tshàu-phú-tê」，「洱」的文音「jī/jínn」",
  },
  {
    num: 90,
    huagi: "虎鯨,殺人鯨",
    taigiHan: "油鯃",
    taigiLo: "iû-ngôo",
    guagi: "",
    tsukai: "http://studentweb.bhes.ntpc.edu.tw/91s/s860323/www/new_page_7.htm",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "虎鯨",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "建議直接照生物分類講「虎鯨」",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo:
      "建議收「虎鯨 hóo-king」、「虎海翁 hóo-hái-ang」、「殺手海翁 sat-tshiú hái-ang」",
  },
  {
    num: 91,
    huagi: "子宮頸癌",
    taigiHan: "子宮喙癌",
    taigiLo: "tsú-kiong-tshuì-gâm",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "子宮頭、子宮喙攏有人講",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "子宮頭癌?",
    phioTshi: "應討論",
    tsuTshi: "子宮頭癌",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「子宮頷癌 tsú-kiong-ām-gâm」",
  },
  {
    num: 92,
    huagi: "玉米棒",
    taigiHan: "番麥枝, 番麥條",
    taigiLo: "huan-be̍h-ki, huan-be̍h-tiâu",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "番麥枝，一枝番麥枝",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "番麥枝 huan-be̍h-ki",
    phioHo: "應討論",
    tsuHo: "番麥枝",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「番麥枝 huan-be̍h-ki」",
  },
  {
    num: 93,
    huagi: "甘地",
    taigiHan: "顏智",
    taigiLo: "Gân-tī",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "顏智 Gân-tì",
    phioHo: "認同",
    tsuHo: "Gân-tì",
    phioKueh: "應討論",
    tsuKueh: "看各位委員先進敢欲改現代翻譯「甘地」（Kam-tī）",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「甘地 Kam-tī」 、「顏智 Gân-tì」",
  },
  {
    num: 94,
    huagi: "手搖杯飲料店",
    taigiHan: "手摵茶涼水店,手搖杯飲料店",
    taigiLo: "tshiú-tshik-tê liâng-tsuí-tiàm,tshiú-tshik-tê ím-liāu-tiàm",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "摵仔杯飲料店",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "手摵茶飲料店 tshiú-tshi̍k-tê ím-liāu-tiàm",
    phioHo: "應討論",
    tsuHo: "摵茶店",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「手摵飲料店 tshiú-tshi̍k ím-liāu-tiàm」",
  },
  {
    num: 95,
    huagi: "櫻花鉤吻鮭",
    taigiHan: "本邦,紋斑",
    taigiLo: "pún-pang,bûn-pan",
    guagi: "",
    tsukai: "itaigi",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "紋斑",
    phioLim: "應討論",
    tsuLim:
      "鮭科>麻哈魚屬>櫻鱒(種)>亞種。新分類。建議「臺灣櫻鱒Tâi-uân îng-tsún」or「臺灣櫻鮭Tâi-uân îng-kui」。https://fishdb.sinica.edu.tw/chi/species.php?id=382788",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "紋斑 bûn-pan",
    phioHo: "應討論",
    tsuHo:
      "稱呼真濟款, 會當討論看beh用泰雅語的紋斑?日語的sa-khuh-lah má-suh? Iah是像台灣紅鰱魚/櫻花紅鰱魚這款新創的叫法",
    phioKueh: "認同",
    tsuKueh: "在地人講泰雅族的音「Bunban」",
    phioTshi: "認同",
    tsuTshi: "台灣鱒",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「河鮘hô-tāi」、「紋斑bûn-pan」。「本邦」「紋斑」是仝詞無仝轉音。",
  },
  {
    num: 96,
    huagi: "儲能設施,儲電設施",
    taigiHan: "儉能設施,儉電設施",
    taigiLo: "khiām-lîng siat-si, khiām-tiān siat-si",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "儲",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "頂改有講蓄、儲莫翻做儉？抑是翻做儉無要緊？袂記得矣。",
    phioGiam: "應討論",
    tsuGiam: "照漢字念",
    phioThiann: "認同",
    tsuThiann:
      "蓄電設施 thiok-tiān siat-si 【案：《臺日》是有收「蓄電池thiok-tiān-tî」，閣再，台語在來也有「蓄積thiok-tsik」抑是「積蓄tsik-thiok」的講法。】",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "抑是直接用tû-lîng siat-si",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo:
      "建議直接照字講做「儲能設施 tû-lîng siat-si, 儲電設施tû-tiān siat-si」",
  },
  {
    num: 97,
    huagi: "踩踏事件",
    taigiHan: "人踏人事件",
    taigiLo: "lâng-ta̍h-lâng sū-kiānn",
    guagi: "",
    tsukai: "人踏人事件、人踏人意外",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "𧿬踏事件？(濟人𧿬踏)",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "𧿬踏 （thún-ta̍h）事件",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議收「相踏事件sio-ta̍h sū-kiānn」",
  },
  {
    num: 98,
    huagi: "班腿樹蛙",
    taigiHan: "班腿樹蛤仔",
    taigiLo: "pan-thuí tshiū-kap-á",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "斑腿青虳 pan-thuí-tshenn-ioh / pan-thuí-tshinn-ioh",
    phioHo: "應討論",
    tsuHo: '贊同"斑"腿青ioh, 也會當講是香港青ioh(á)',
    phioKueh: "應討論",
    tsuKueh: "pan-thuí tshiū-ua",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "應該是「斑腿樹蛤仔 pan-thuí-tshiū-kap-á」",
  },
  {
    num: 99,
    huagi: "爵士樂",
    taigiHan: "爵士樂",
    taigiLo: "tsiok-sū-ga̍k",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "jiah-sir",
    phioTsng: "應討論",
    tsuTsng: "直接講Jazz",
    phioLim: "應討論",
    tsuLim: "jazz 樂",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "應討論",
    tsuHo: '聽現場歌手攏講"Jià-zuh"',
    phioKueh: "應討論",
    tsuKueh: "jazz-ga̍k",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 100,
    huagi: "蓮蓬頭",
    taigiHan: "蓮花頭",
    taigiLo: "liân-hue-thâu",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "蓮房頭liân-pông-thâu。蓮蓬是蓮房、蓮花房、蓮苞pô、蓮花頭。愛加「頭」來區分",
    phioGiam: "應討論",
    tsuGiam: "蓮蓬頭liân-phông-thâu",
    phioThiann: "認同",
    tsuThiann: "蓮花頭liân-hue-thâu；蓮苞頭 liân-pôo-thâu",
    phioHo: "認同",
    tsuHo: "蓮花頭",
    phioKueh: "應討論",
    tsuKueh: "有人講「蓮花頭」，抑是直接講shower",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「蓮苞頭 liân-pôo-thâu」",
  },
  {
    num: 101,
    huagi: "跨欄",
    taigiHan: "迒欄",
    taigiLo: "hānn-nuâ",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "迒欄hānn-lân",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "跨欄 khuà-lân",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議照文音直接講做「跨欄khuà-lân」",
  },
  {
    num: 102,
    huagi: "生成式",
    taigiHan: "生湠式,生成式",
    taigiLo: "senn-thuànn-sik,sing-sîng-sik",
    guagi: "generative",
    tsukai: "相關詞彙：生成式人工智慧、生成式演算法、生成式藝術",
    phioKhoo: "應討論",
    tsuKhoo: "生成式",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim:
      "毋是生湠，佮生成語法的生成倚意。想欲建議用sing-sîng，毋過漢字「生成」咱有固定閣捷用的意思。",
    phioGiam: "應討論",
    tsuGiam: "生成式",
    phioThiann: "應討論",
    tsuThiann: "生成式 sing-sîng-sik",
    phioHo: "認同",
    tsuHo: "生成式",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議照字講做「生成式 sing-sîng-sik」",
  },
  {
    num: 103,
    huagi: "滯洪池",
    taigiHan: "抾水池",
    taigiLo: "khioh-tsuí-tî",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "認同",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "滯洪池 tī-hông-tî",
    phioHo: "應討論",
    tsuHo: "會當考慮滯水池",
    phioKueh: "應討論",
    tsuKueh: "滯水池，臺日有收滯水（tù-chúi）",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "建議照字講做「滯洪池tī-hông-tî」",
  },
  {
    num: 104,
    huagi: "惡地",
    taigiHan: "泥岩地",
    taigiLo: "nî-giâm-tē",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "建議惡地就好",
    phioGiam: "認同",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "惡地 ok-tē / ok-tuē",
    phioHo: "認同",
    tsuHo: "惡地",
    phioKueh: "應討論",
    tsuKueh: "建議直接講「惡地」",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "建議直接講做「惡地ok-tē/tuē」",
  },
  {
    num: 105,
    huagi: "側面了解",
    taigiHan: "對別位探聽",
    taigiLo: "tuì pa̍t-uī thàm-thiann",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "(這條已經有討論過)",
    phioLim: "應討論",
    tsuLim: "頂改有討論？tshik-bīn liáu-kái",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "認同",
    tsuThiann: "",
    phioHo: "認同",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "探聽消息",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「坦邊探聽 thán-pinn thàm-thiann」",
  },
  {
    num: 106,
    huagi: "桌上遊戲,桌遊",
    taigiHan: "桌仔耍",
    taigiLo: "toh-á-sńg",
    guagi: "",
    tsukai: "",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "桌頂耍",
    phioLim: "應討論",
    tsuLim: "桌頂遊戲，桌遊",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann:
      "桌遊 toh-iû；桌頂𨑨迌物仔 toh-tíng tshit-thô-mih-á / toh-tíng thit-thô-mih-á",
    phioHo: "應討論",
    tsuHo: '也有聽講叫做"桌頂弈"的, 會當討論看覓',
    phioKueh: "應討論",
    tsuKueh: "toh-iû，臺日有收「遊戲」這个詞",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "認同",
    tsuLoo: "",
  },
  {
    num: 107,
    huagi: "折疊手機",
    taigiHan: "拗遏手機",
    taigiLo: "áu-at-tshiú-ki",
    guagi: "",
    tsukai: "itaigi建議",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "「拗手機仔」會成動賓，建議拗式手機仔、拗式機仔",
    phioGiam: "應討論",
    tsuGiam: "摺拗 tsih-áu ／拗合 áu-ha̍p",
    phioThiann: "應討論",
    tsuThiann: "拗摺式手機仔 áu-tsih-sik tshiú-ki-á",
    phioHo: "應討論",
    tsuHo: "拗遏",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「拗折手機 áu-tsi̍h tshiú-ki」",
  },
  {
    num: 108,
    huagi: "折疊腳踏車",
    taigiHan: "拗遏跤踏車",
    taigiLo: "áu-at-kha-ta̍h-tshia",
    guagi: "",
    tsukai: "itaigi建議",
    phioKhoo: "認同",
    tsuKhoo: "",
    phioTsng: "認同",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "拗式跤踏車",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "拗摺式跤踏車 áu-tsih-sik kha-ta̍h-tshia",
    phioHo: "應討論",
    tsuHo: '"拗遏"這个詞khah無好發音, 驚社會接受度khah低 \n',
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「拗折跤踏車 áu-tsi̍h kha-ta̍h-tshia」",
  },
  {
    num: 109,
    huagi: "饒舌",
    taigiHan: "喋舌,弄舌",
    taigiLo: "thi̍h-tsi̍h, lāng-tsi̍h",
    guagi: "",
    tsukai:
      "這个講法來自 《文化相放伴》#28 喋舌音樂是啥物 來聽臺灣喋舌的故事，主持人講以早伊佮田孟淑田媽媽開講的時陣田媽媽發明的講法（毋過阿雞是唸thih53tsih53）",
    phioKhoo: "認同",
    tsuKhoo: "弄舌",
    phioTsng: "認同",
    tsuTsng: "弄舌",
    phioLim: "應討論",
    tsuLim: "錦舌，取盤喙錦的錦",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "弄舌 lāng-tsi̍h",
    phioHo: "應討論",
    tsuHo:
      '是beh翻"饒舌"(罵人)? Iah是"饒舌歌"? 一个有負面的意思, 一个無, 翻譯的時無定就會無仝',
    phioKueh: "應討論",
    tsuKueh: "哺舌（pōo-tsi̍h ）",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「盤舌 puânn-tsi̍h」、饒舌歌「盤舌歌 puânn-tsi̍h-kua」",
  },
  {
    num: 110,
    huagi: "泛舟",
    taigiHan: "划船",
    taigiLo: "kò-tsûn",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "",
    phioLim: "應討論",
    tsuLim: "浮船（泛是浮的意思",
    phioGiam: "應討論",
    tsuGiam: "",
    phioThiann: "應討論",
    tsuThiann: "泛舟 huàn-tsiu",
    phioHo: "認同",
    tsuHo: "泛舟",
    phioKueh: "認同",
    tsuKueh: "",
    phioTshi: "認同",
    tsuTshi: "",
    phioSoo: "應討論",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「放流船 pàng-lâu-tsûn」",
  },
  {
    num: 111,
    huagi: "電烙鐵,電焊筆",
    taigiHan: "熨錫,黏錫",
    taigiLo: "ut-siah,liâm-siah",
    guagi: "",
    tsukai: "",
    phioKhoo: "應討論",
    tsuKhoo: "",
    phioTsng: "應討論",
    tsuTsng: "敢有一般的用法?",
    phioLim: "",
    tsuLim: "",
    phioGiam: "應討論",
    tsuGiam: "電銲筆tiān-huānn-pit（教典huānn用「銲」字）",
    phioThiann: "應討論",
    tsuThiann: "電銲筆 tiān-huānn-pit",
    phioHo: "應討論",
    tsuHo: "",
    phioKueh: "應討論",
    tsuKueh: "敢若有講「熨斗」，形看起來像「電燒筆」?",
    phioTshi: "應討論",
    tsuTshi: "",
    phioSoo: "認同",
    tsuSoo: "",
    phioLoo: "應討論",
    tsuLoo: "「電燒鐵 tiān-sio-thih、電燒筆 tiān-sio-pit」",
  },
];
